import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { getPostgresPoolConfig } from '../config/db-postgres.js';
import { validatePostgresTestGuard } from '../config/postgres-guard.js';
import { calculateChecksum } from '../database/postgres/migrate.js';
import { createPaymentAttemptsRepository, PaymentAttemptError } from '../repositories/postgres/payment-attempts.js';
import { createDirectPayOSAttemptService } from '../services/direct-payos-attempt.js';
import { createGroupedPayOSAttemptService } from '../services/grouped-payos-attempt.js';
import { processPayOSWebhookWithAttempts } from '../services/payment-attempt-settlement.js';
import { reconcilePayOSAttempt } from '../services/payos-reconciliation.js';

const { Pool } = pg;
const enabled = process.env.POSTGRES_INTEGRATION === '1';
const testDbUrl = process.env.TEST_DATABASE_URL;
const root = path.dirname(fileURLToPath(import.meta.url));
const migration0026 = path.join(root, '..', 'database', 'postgres', 'migrations', '0026_payment_attempts_additive.sql');
const migration0027 = path.join(root, '..', 'database', 'postgres', 'migrations', '0027_payment_attempts_enforcement.sql');
const preflight0027 = path.join(root, '..', 'database', 'postgres', 'verification', '0027_payment_attempts_preflight_readonly.sql');

function schemaName() {
  return `p1_rollout_${crypto.randomBytes(6).toString('hex')}`;
}

let lastStartedPhase = 'none';
async function runPhase(name, work, timeoutMs = 45_000, onTimeout = null) {
  lastStartedPhase = name;
  console.log(`[P1 rehearsal] BEFORE ${name}`);
  let timer;
  try {
    const result = await Promise.race([
      work(),
      new Promise((_, reject) => {
        timer = setTimeout(() => reject(new Error(`PHASE_TIMEOUT ${name} after ${timeoutMs}ms; last_started_phase=${lastStartedPhase}; open_handles=runner-managed`)), timeoutMs);
        timer.unref?.();
      }),
    ]);
    console.log(`[P1 rehearsal] AFTER ${name}`);
    return result;
  } catch (error) {
    if (String(error?.message || '').startsWith('PHASE_TIMEOUT') && onTimeout) {
      try { console.error(`[P1 rehearsal] TIMEOUT_DIAGNOSTICS ${JSON.stringify(await onTimeout())}`); } catch (diagnosticError) {
        console.error(`[P1 rehearsal] TIMEOUT_DIAGNOSTICS_FAILED code=${diagnosticError?.code || 'unknown'}`);
      }
    }
    console.error(`[P1 rehearsal] FAILED ${name}: ${error?.message || String(error)}`);
    throw error;
  } finally {
    if (timer) clearTimeout(timer);
  }
}

async function createPost0025Baseline(client, schema) {
  await client.query(`CREATE SCHEMA "${schema}"`);
  await client.query(`SET search_path TO "${schema}", public`);
  await client.query(`
    CREATE TABLE payment_profiles (code VARCHAR(50) PRIMARY KEY);
    CREATE TABLE checkout_groups (
      id BIGINT PRIMARY KEY, group_code VARCHAR(50), total_amount NUMERIC(15,2) NOT NULL,
      user_id BIGINT, payment_provider VARCHAR(30) NOT NULL DEFAULT 'payos', payment_status VARCHAR(30) NOT NULL,
      payment_profile_code VARCHAR(50) NOT NULL, payment_profile_version INT,
      payment_link_id VARCHAR(100), payos_order_code BIGINT, payment_checkout_url TEXT, payment_qr_code TEXT,
      payment_created_at TIMESTAMPTZ, payment_expires_at TIMESTAMPTZ, paid_at TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE orders (
      id BIGINT PRIMARY KEY, order_code VARCHAR(50), user_id BIGINT, cancel_token_hash VARCHAR(255), total NUMERIC(15,2) NOT NULL,
      checkout_group_id BIGINT, payment_provider VARCHAR(30), payment_status VARCHAR(20) NOT NULL, current_status VARCHAR(30),
      payment_profile_code VARCHAR(50), payment_profile_version INT, payment_link_id VARCHAR(100), payos_order_code BIGINT,
      payment_checkout_url TEXT, payment_qr_code TEXT, payment_created_at TIMESTAMPTZ, payment_expires_at TIMESTAMPTZ,
      paid_at TIMESTAMPTZ, transaction_id VARCHAR(255), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE payment_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider VARCHAR(50) NOT NULL,
      provider_event_key VARCHAR(255) NOT NULL UNIQUE, order_id BIGINT, event_type VARCHAR(100) NOT NULL,
      payload JSONB NOT NULL DEFAULT '{}'::jsonb, processing_status VARCHAR(50) NOT NULL DEFAULT 'pending',
      error_code VARCHAR(100), processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE schema_migrations (
      version VARCHAR(50) PRIMARY KEY, name VARCHAR(255) NOT NULL, checksum VARCHAR(64) NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO payment_profiles VALUES ('DIRECT_A'), ('GROUP_CHECKOUT');
    INSERT INTO checkout_groups (id, group_code, total_amount, user_id, payment_status, payment_profile_code, payment_profile_version)
    VALUES (10, 'GRP-ROLLOUT-10', 50000, 9, 'unpaid', 'GROUP_CHECKOUT', 1),
           (11, 'GRP-ROLLOUT-11', 51000, 9, 'unpaid', 'GROUP_CHECKOUT', 1);
    INSERT INTO orders (id, order_code, user_id, total, checkout_group_id, payment_provider, payment_status, current_status, payment_profile_code, payment_profile_version)
    VALUES (1, 'ORD-ROLLOUT-1', 9, 10000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (2, 'ORD-ROLLOUT-2', 9, 20000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (3, 'ORD-ROLLOUT-3', 9, 30000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (4, 'ORD-ROLLOUT-4', 9, 40000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (5, 'ORD-ROLLOUT-5', 9, 50000, 10, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (6, 'ORD-ROLLOUT-6', 9, 25000, 10, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (7, 'ORD-ROLLOUT-7', 9, 51000, 11, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1);
  `);
}

function database(client) {
  const query = async (sql, params = []) => {
    const result = await client.query(sql, params);
    return [result.rows, result.rowCount ?? 0];
  };
  return {
    query,
    transaction: async (runner) => {
      await client.query('BEGIN');
      try {
        const result = await runner({ query });
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => {});
        throw error;
      }
    },
  };
}

function safeSqlLabel(sql) {
  const text = String(sql).replace(/\s+/g, ' ').trim();
  if (/FROM orders WHERE id = \$1 FOR UPDATE/i.test(text)) return 'lockTarget(order)';
  if (/FROM checkout_groups WHERE id = \$1 FOR UPDATE/i.test(text)) return 'lockTarget(group)';
  if (/FROM payment_attempts WHERE id = \$1 FOR UPDATE/i.test(text)) return 'findAttemptForUpdate';
  if (/UPDATE payment_attempts/i.test(text)) return 'markAttemptPaid/update_attempt';
  if (/UPDATE (orders|checkout_groups)/i.test(text)) return 'mirror_or_pointer_update';
  if (/INSERT INTO payment_events/i.test(text)) return 'payment_event_insert';
  if (/UPDATE payment_events/i.test(text)) return 'payment_event_update';
  return 'query';
}

async function readOnlyLockDiagnostics(testDbUrl, pid) {
  const diagnosticPool = new Pool(getPostgresPoolConfig(testDbUrl));
  const diagnosticClient = await diagnosticPool.connect();
  try {
    const activity = await diagnosticClient.query(`
      SELECT pid, pg_blocking_pids(pid) AS blockers, wait_event_type, wait_event, state,
             backend_xid IS NOT NULL AS has_backend_xid
      FROM pg_stat_activity WHERE pid = $1
    `, [pid]);
    const blockerPids = activity.rows[0]?.blockers || [];
    const locks = await diagnosticClient.query(`
      SELECT l.pid, l.locktype, l.mode, l.granted,
             CASE WHEN l.relation IS NULL THEN NULL ELSE l.relation::regclass::text END AS relation,
             l.classid, l.objid, l.objsubid
      FROM pg_locks l
      WHERE l.pid = $1 OR l.pid = ANY($2::int[])
    `, [pid, blockerPids]);
    const blockerActivity = blockerPids.length
      ? await diagnosticClient.query(`
          SELECT pid, pg_blocking_pids(pid) AS blockers, wait_event_type, wait_event, state,
                 backend_xid IS NOT NULL AS has_backend_xid
          FROM pg_stat_activity WHERE pid = ANY($1::int[])
        `, [blockerPids])
      : { rows: [] };
    return {
      blocked_pid: pid,
      blocked_activity: activity.rows,
      blocker_activity: blockerActivity.rows,
      locks: locks.rows,
      blocker_classification: blockerPids.map((blockerPid) => ({ pid: blockerPid, owner: 'unknown_external_or_previous_substep' })),
    };
  } finally {
    diagnosticClient.release();
    await diagnosticPool.end();
  }
}

async function runLatePaidDiagnostic({ client, testDbUrl, repo, attemptId }) {
  const [{ pid }] = (await client.query('SELECT pg_backend_pid() AS pid')).rows;
  await client.query("SET lock_timeout = '2s'");
  await client.query("SET statement_timeout = '8s'");
  const started = Date.now();
  let timeoutHandle;
  console.log(`[P1 late-paid] session purpose=late-paid transaction backend_pid=${pid}`);
  console.log(`[P1 late-paid] connection tags purpose=direct-create/regenerate,grouped-create/regenerate,webhook,reconciliation,expiry,late-paid transaction backend_pid=${pid}`);
  const originalQuery = client.query.bind(client);
  client.query = async (sql, params) => {
    const label = safeSqlLabel(sql);
    if (label !== 'query') console.log(`[P1 late-paid] BEFORE ${label}`);
    try {
      const result = await originalQuery(sql, params);
      if (label !== 'query') console.log(`[P1 late-paid] AFTER ${label}`);
      return result;
    } catch (error) {
      if (label !== 'query') console.error(`[P1 late-paid] ERROR ${label} code=${error?.code || 'unknown'}`);
      throw error;
    }
  };
  try {
    console.log('[P1 late-paid] BEFORE transaction begin');
    const result = await Promise.race([
      repo.processSuccessfulAttemptEvent({
        attemptId, provider: 'payos', providerPaymentIdentity: 'reference:late-group',
        amount: 51000, reference: 'late-group', paymentLinkId: 'expire-group',
      }),
      new Promise((_, reject) => {
        timeoutHandle = setTimeout(async () => {
          try {
            const diagnostics = await readOnlyLockDiagnostics(testDbUrl, pid);
            console.error(`[P1 late-paid] TIMEOUT_DIAGNOSTICS ${JSON.stringify(diagnostics)}`);
          } catch (diagnosticError) {
            console.error(`[P1 late-paid] TIMEOUT_DIAGNOSTICS_FAILED code=${diagnosticError?.code || 'unknown'}`);
          }
          reject(Object.assign(new Error('LATE_PAID_TIMEOUT'), { code: 'LATE_PAID_TIMEOUT' }));
        }, 4_000);
      }),
    ]);
    console.log('[P1 late-paid] AFTER transaction commit');
    return result;
  } catch (error) {
    console.error(`[P1 late-paid] FAILED class=${error?.name || 'Error'} code=${error?.code || 'unknown'} elapsed_ms=${Date.now() - started}`);
    if (error?.code === 'LATE_PAID_TIMEOUT' || error?.code === '55P03' || error?.code === '57014') {
      console.error(`[P1 late-paid] DIAGNOSTICS ${JSON.stringify(await readOnlyLockDiagnostics(testDbUrl, pid))}`);
    }
    console.error('[P1 late-paid] AFTER transaction rollback');
    throw error;
  } finally {
    if (timeoutHandle) clearTimeout(timeoutHandle);
    client.query = originalQuery;
    await client.query("RESET lock_timeout");
    await client.query("RESET statement_timeout");
  }
}

async function applyTrackedMigration(client, version, filename, sql) {
  await client.query('BEGIN');
  try {
    if (version === '0026') {
      await client.query(`CREATE TEMP TABLE p1_legacy_quarantine_manifest_input (target_kind text NOT NULL, target_id bigint NOT NULL, classification text NOT NULL, classifier_version text NOT NULL) ON COMMIT DROP`);
    }
    await client.query(sql);
    await client.query(
      'INSERT INTO schema_migrations (version, name, checksum) VALUES ($1, $2, $3)',
      [version, filename, calculateChecksum(sql)],
    );
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  }
}

function makePayOSHarness(prefix) {
  let sequence = 0;
  return {
    lookupPaymentLink: async () => ({ kind: 'not_found' }),
    createPaymentLink: async ({ payosOrderCode }) => {
      sequence += 1;
      return {
        paymentLinkId: `${prefix}-link-${sequence}`,
        checkoutUrl: `https://payos.test/${prefix}/${payosOrderCode}`,
        qrCode: `${prefix}-qr-${sequence}`,
      };
    },
  };
}

describe('Post-0025 staging P1 rollout rehearsal', () => {
  it('runs 0026 runtime smoke, zero-block preflight, then 0027 enforcement regression', async (t) => {
    if (!enabled || !testDbUrl) return t.skip('Requires POSTGRES_INTEGRATION=1 and TEST_DATABASE_URL');
    assert.equal(validatePostgresTestGuard(testDbUrl).valid, true);
    const [sql0026, sql0027, preflight] = await Promise.all([
      readFile(migration0026, 'utf8'), readFile(migration0027, 'utf8'), readFile(preflight0027, 'utf8'),
    ]);
    const pool = new Pool(getPostgresPoolConfig(testDbUrl));
    const client = await pool.connect();
    const schema = schemaName();
    try {
      await runPhase('prepare post-0025 isolated staging state', () => createPost0025Baseline(client, schema));
      await runPhase('0026 apply', () => applyTrackedMigration(client, '0026', '0026_payment_attempts_additive.sql', sql0026));
      await runPhase('verify 0026 schema/backfill/quarantine', async () => {
        const result = await client.query(`SELECT to_regclass('payment_attempts') AS attempts, to_regclass('legacy_payment_quarantine_manifest') AS quarantine`);
        assert.equal(result.rows[0].attempts, 'payment_attempts');
        assert.equal(result.rows[0].quarantine, 'legacy_payment_quarantine_manifest');
      });
      const repo = createPaymentAttemptsRepository(database(client));
      const now = () => new Date('2026-09-07T00:00:00.000Z');
      let code = 90100000000000;
      const directPayOS = makePayOSHarness('direct');
      const groupPayOS = makePayOSHarness('group');
      const direct = createDirectPayOSAttemptService({
        attemptsRepository: repo, ...directPayOS, now, makeProviderOrderCode: () => ++code,
        withCreationLock: async (_key, callback) => callback({ acquired: true }),
      });
      const group = createGroupedPayOSAttemptService({
        attemptsRepository: repo, ...groupPayOS, now, makeProviderOrderCode: () => ++code,
        groupsRepository: { findGroupByCode: async () => ({ id: 10, group_code: 'GRP-ROLLOUT-10', total_amount: 50000, user_id: 9, payment_status: 'unpaid', payment_profile_code: 'GROUP_CHECKOUT', payment_profile_version: 1 }) },
        withCreationLock: async (_key, callback) => callback({ acquired: true }),
      });

      if (process.env.P1_LOCK_DIAGNOSTICS === '1') {
        for (const method of ['markAttemptPaid', 'processSuccessfulAttemptEvent']) {
          const original = repo[method].bind(repo);
          repo[method] = async (...args) => {
            console.log(`[P1 late-paid] BEFORE ${method}`);
            try {
              const result = await original(...args);
              console.log(`[P1 late-paid] AFTER ${method}`);
              return result;
            } catch (error) {
              console.error(`[P1 late-paid] ERROR ${method} code=${error?.code || 'unknown'}`);
              throw error;
            }
          };
        }
      }

      if (process.env.P1_LATE_PAID_ONLY === '1') {
        await runPhase('isolated grouped late-paid setup', async () => {
          const creating = await repo.reserveOrRecoverCreatingAttempt({
            checkoutGroupId: 11, paymentProfileCode: 'GROUP_CHECKOUT', amount: 51000,
            providerOrderCode: ++code, expiresAt: '2026-09-06T23:00:00.000Z',
          });
          await repo.activateAttempt({
            attemptId: creating.attempt.id, providerOrderCode: creating.attempt.provider_order_code,
            paymentLinkId: 'expire-group', checkoutUrl: 'https://payos.test/expire-group',
            qrCode: 'expire-group', expiresAt: '2026-09-06T23:00:00.000Z',
          });
          await repo.expireAttempt({ attemptId: creating.attempt.id, expiredAt: '2026-09-07T00:00:00.000Z' });
          const paid = await runLatePaidDiagnostic({ client, testDbUrl, repo, attemptId: creating.attempt.id });
          assert.equal(paid.kind, 'paid');
        });
        return;
      }

      // Runtime on 0026 only: direct and group create/regenerate retain legacy response fields.
      const directTarget = { id: 1, order_code: 'ORD-ROLLOUT-1', user_id: 9, total: 10000, payment_provider: 'payos', payment_status: 'unpaid', current_status: 'pending', payment_profile_code: 'DIRECT_A', payment_profile_version: 1, checkout_group_id: null };
      await runPhase('P1 runtime checks on 0026', async () => {
      const directFirst = await runPhase('direct create', () => direct.createForOrder({ order: directTarget, paymentProfile: { code: 'DIRECT_A', version: 1 } }), 10_000);
      assert.equal(directFirst.payment_link_id, 'direct-link-1');
      const directReplacement = await runPhase('direct regenerate', () => direct.regenerateForCustomer({ orderCode: 'ORD-ROLLOUT-1', userId: 9 }), 10_000);
      assert.equal(directReplacement.payment_link_id, 'direct-link-2');
      const groupTarget = { id: 10, group_code: 'GRP-ROLLOUT-10', total_amount: 50000, payment_provider: 'payos', payment_status: 'unpaid', payment_profile_code: 'GROUP_CHECKOUT', payment_profile_version: 1 };
      const groupFirst = await runPhase('grouped create', () => group.createForGroup({ group: groupTarget }), 10_000);
      assert.equal(groupFirst.payment_link_id, 'group-link-1');
      const groupReplacement = await runPhase('grouped regenerate', () => group.regenerateForCustomer({ groupCode: 'GRP-ROLLOUT-10', userId: 9 }), 10_000);
      assert.equal(groupReplacement.payment_link_id, 'group-link-2');

      // Webhook settlement: an old superseded direct QR can still settle and wins atomically.
      const oldDirect = (await repo.findAttemptsByTarget({ orderId: 1 })).find((attempt) => attempt.status === 'superseded');
      const webhook = await runPhase('webhook resolution', () => processPayOSWebhookWithAttempts({
        body: { data: { orderCode: oldDirect.provider_order_code, paymentLinkId: oldDirect.provider_payment_link_id, amount: 10000, reference: 'webhook-direct-old', code: '00' } },
        attemptsRepository: repo,
        verifyWebhook: async (body, { profileCode }) => {
          assert.equal(profileCode, 'DIRECT_A');
          return body.data;
        },
      }), 10_000);
      assert.equal(webhook.kind, 'paid');
      const directAfterWebhook = await repo.findAttemptsByTarget({ orderId: 1 });
      assert.equal(directAfterWebhook.filter((attempt) => attempt.status === 'paid').length, 1);

      // Reconciliation settles the active direct target through the same event identity/lifecycle.
      const reconcileAttempt = await repo.reserveOrRecoverCreatingAttempt({ orderId: 2, paymentProfileCode: 'DIRECT_A', amount: 20000, providerOrderCode: ++code, expiresAt: '2026-09-07T00:15:00.000Z' });
      const activeForReconcile = await repo.activateAttempt({ attemptId: reconcileAttempt.attempt.id, providerOrderCode: reconcileAttempt.attempt.provider_order_code, paymentLinkId: 'recon-link', checkoutUrl: 'https://payos.test/recon', qrCode: 'recon-qr', expiresAt: '2026-09-07T00:15:00.000Z' });
      const reconciliation = await runPhase('reconciliation', () => reconcilePayOSAttempt({
        attempt: activeForReconcile,
        attemptsRepository: repo,
        getPaymentInfo: async () => ({ status: 'PAID', amountPaid: 20000, id: 'recon-link', reference: 'recon-reference' }),
      }), 10_000);
      assert.equal(reconciliation.changed, true);

      // Expiry is idempotent for direct and group; valid late evidence still settles expired/group state.
      const expiringDirect = await runPhase('prepare expiry direct attempt', () => repo.reserveOrRecoverCreatingAttempt({ orderId: 3, paymentProfileCode: 'DIRECT_A', amount: 30000, providerOrderCode: ++code, expiresAt: '2026-09-06T23:00:00.000Z' }), 10_000);
      await runPhase('activate expiry direct attempt', () => repo.activateAttempt({ attemptId: expiringDirect.attempt.id, providerOrderCode: expiringDirect.attempt.provider_order_code, paymentLinkId: 'expire-direct', checkoutUrl: 'https://payos.test/expire-direct', qrCode: 'expire-direct', expiresAt: '2026-09-06T23:00:00.000Z' }), 10_000);
      const expiringGroup = await runPhase('prepare expiry grouped attempt', () => repo.reserveOrRecoverCreatingAttempt({ checkoutGroupId: 11, paymentProfileCode: 'GROUP_CHECKOUT', amount: 51000, providerOrderCode: ++code, expiresAt: '2026-09-06T23:00:00.000Z' }), 10_000);
      await runPhase('activate expiry grouped attempt', () => repo.activateAttempt({ attemptId: expiringGroup.attempt.id, providerOrderCode: expiringGroup.attempt.provider_order_code, paymentLinkId: 'expire-group', checkoutUrl: 'https://payos.test/expire-group', qrCode: 'expire-group', expiresAt: '2026-09-06T23:00:00.000Z' }), 10_000);
      const firstExpiry = await runPhase('expiry direct/group', () => repo.expireDuePaymentAttempts({ now: '2026-09-07T00:00:00.000Z' }), 10_000);
      const rerunExpiry = await runPhase('expiry rerun idempotency', () => repo.expireDuePaymentAttempts({ now: '2026-09-07T00:00:00.000Z' }), 10_000);
      assert.equal(firstExpiry.length, 2);
      assert.equal(rerunExpiry.length, 0);
      const lateGroupPaid = await runPhase(
        'late-paid after expired/superseded',
        () => runLatePaidDiagnostic({ client, testDbUrl, repo, attemptId: expiringGroup.attempt.id }),
        process.env.P1_LOCK_CAPTURE === '1' ? 120_000 : 10_000,
        async () => {
          const [{ pid }] = await client.query('SELECT pg_backend_pid() AS pid');
          return readOnlyLockDiagnostics(testDbUrl, pid);
        },
      );
      assert.equal(lateGroupPaid.kind, 'paid');
      const [childAttempts] = await database(client).query('SELECT COUNT(*)::int AS count FROM payment_attempts WHERE order_id IN (5, 6)');
      assert.equal(childAttempts[0].count, 0);
      await runPhase('child artifact barrier', () => assert.rejects(
        () => repo.reserveOrRecoverCreatingAttempt({ orderId: 5, paymentProfileCode: 'DIRECT_A', amount: 50000, providerOrderCode: ++code }),
        (error) => error instanceof PaymentAttemptError && error.code === 'GROUP_CHILD_DIRECT_ATTEMPT_FORBIDDEN',
      ), 10_000);
      }, process.env.P1_LOCK_CAPTURE === '1' ? 120_000 : 45_000);

      // 0027 preflight must be clean before enforcement. No manual cleanup occurs.
      let preflightResult;
      await runPhase('0027 preflight', async () => { preflightResult = await client.query(preflight); });
      assert.equal(preflightResult.rows.every((row) => Number(row.issue_count) === 0 && row.status === 'PASS'), true, JSON.stringify(preflightResult.rows));
      await runPhase('0027 apply', () => applyTrackedMigration(client, '0027', '0027_payment_attempts_enforcement.sql', sql0027));

      // Enforcement regression: constraints preserve P1 flows and reject child attempts/pointer misuse.
      await runPhase('verify constraints/indexes/triggers and post-0027 runtime', async () => {
      const enforced = await repo.reserveOrRecoverCreatingAttempt({ orderId: 4, paymentProfileCode: 'DIRECT_A', amount: 40000, providerOrderCode: ++code, expiresAt: '2026-09-07T00:15:00.000Z' });
      const enforcedActive = await repo.activateAttempt({ attemptId: enforced.attempt.id, providerOrderCode: enforced.attempt.provider_order_code, paymentLinkId: 'enforced-link', checkoutUrl: 'https://payos.test/enforced', qrCode: 'enforced', expiresAt: '2026-09-07T00:15:00.000Z' });
      assert.equal(enforcedActive.status, 'active');
      await assert.rejects(
        () => client.query("INSERT INTO payment_attempts (target_type, order_id, provider, payment_profile_code, amount, status) VALUES ('order', 5, 'payos', 'DIRECT_A', 50000, 'creating')"),
        /grouped child|payment attempt order target/i,
      );
      const tracker = await client.query('SELECT version, name, checksum FROM schema_migrations WHERE version IN ($1, $2) ORDER BY version', ['0026', '0027']);
      assert.deepEqual(tracker.rows.map((row) => row.version), ['0026', '0027']);
      assert.equal(tracker.rows[0].checksum, calculateChecksum(sql0026));
      assert.equal(tracker.rows[1].checksum, calculateChecksum(sql0027));
      const invariantCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_constraint
        WHERE conname IN ('chk_payment_attempts_exactly_one_target', 'fk_orders_current_payment_attempt', 'fk_checkout_groups_current_payment_attempt')
      `);
      assert.equal(invariantCount.rows[0].count, 3);
      const indexCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_indexes
        WHERE indexname IN (
          'uq_payment_attempts_creating_order', 'uq_payment_attempts_creating_group',
          'uq_payment_attempts_provider_profile_order_code', 'uq_payment_attempts_provider_profile_link_id',
          'uq_payment_events_provider_profile_identity'
        )
      `);
      assert.equal(indexCount.rows[0].count, 5);
      const triggerCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_trigger
        WHERE NOT tgisinternal AND tgname IN (
          'trg_payment_attempt_target_0027', 'trg_payment_attempt_immutable_0027',
          'trg_order_current_attempt_0027', 'trg_checkout_group_current_attempt_0027'
        )
      `);
      assert.equal(triggerCount.rows[0].count, 4);
      });
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      client.release();
      await pool.end();
    }
  });
});
