import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { getPostgresPoolConfig } from '../config/db-postgres.js';
import { validatePostgresTestGuard } from '../config/postgres-guard.js';
import { calculateChecksum } from '../database/postgres/migrate.js';

const { Pool } = pg;
const testDbUrl = process.env.TEST_DATABASE_URL;
const enabled = process.env.POSTGRES_INTEGRATION === '1';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const migrationPath = path.join(root, 'database', 'postgres', 'migrations', '0033_preorder_customer_checkin.sql');
const preflightPath = path.join(root, 'database', 'postgres', 'verification', '0033_preorder_customer_checkin_preflight_readonly.sql');
const teaPlusTestProjectRef = 'sumodxrhsbnirvrvnwpy';
const productionProjectRef = 'duahwveccxdtueweyfov';

function schemaName() {
  return `preorder_checkin_0033_${crypto.randomBytes(6).toString('hex')}`;
}

async function createPost0032Baseline(client, schema) {
  await client.query(`CREATE SCHEMA "${schema}"`);
  await client.query(`SET search_path TO "${schema}", public`);
  await client.query(`
    CREATE TABLE schema_migrations (
      version VARCHAR(40) PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      checksum VARCHAR(64) NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE users (
      id BIGINT PRIMARY KEY, fullname TEXT NOT NULL, email TEXT,
      admin_role VARCHAR(40), admin_branch_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE,
      token_version INTEGER NOT NULL DEFAULT 1
    );
    CREATE TABLE stores (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE tables (id BIGINT PRIMARY KEY, store_id BIGINT NOT NULL REFERENCES stores(id), name TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE);
    CREATE TABLE checkout_groups (id BIGINT PRIMARY KEY);
    CREATE TABLE preorders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      preorder_code VARCHAR(40) NOT NULL UNIQUE,
      store_id BIGINT NOT NULL REFERENCES stores(id),
      customer_user_id BIGINT NOT NULL REFERENCES users(id),
      checkout_idempotency_key VARCHAR(100) NOT NULL,
      scheduled_start_at TIMESTAMPTZ NOT NULL,
      scheduled_end_at TIMESTAMPTZ NOT NULL,
      status VARCHAR(40) NOT NULL,
      responsible_manager_id BIGINT NOT NULL REFERENCES users(id),
      checked_in_at TIMESTAMPTZ NULL,
      checkout_group_id BIGINT REFERENCES checkout_groups(id)
    );
    CREATE TABLE preorder_confirmation_incidents (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      preorder_id BIGINT NOT NULL REFERENCES preorders(id),
      manager_id BIGINT NOT NULL REFERENCES users(id),
      incident_type VARCHAR(40) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE manager_preorder_strikes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      manager_id BIGINT NOT NULL REFERENCES users(id),
      incident_id BIGINT NOT NULL REFERENCES preorder_confirmation_incidents(id),
      preorder_id BIGINT NOT NULL REFERENCES preorders(id),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE preorder_notification_deliveries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      preorder_id BIGINT NOT NULL REFERENCES preorders(id),
      channel VARCHAR(40) NOT NULL,
      status VARCHAR(40) NOT NULL DEFAULT 'queued',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE orders (
      id BIGINT PRIMARY KEY, store_id BIGINT NOT NULL REFERENCES stores(id), user_id BIGINT REFERENCES users(id),
      checkout_group_id BIGINT REFERENCES checkout_groups(id), current_payment_attempt_id BIGINT,
      preorder_id BIGINT REFERENCES preorders(id)
    );
  `);

  const migrationsDir = path.join(root, 'database', 'postgres', 'migrations');
  for (let v = 26; v <= 32; v += 1) {
    const ver = String(v).padStart(4, '0');
    // Find matching migration file
    const migrationFiles = {
      '0026': '0026_payment_attempts_additive.sql',
      '0027': '0027_payment_attempts_enforcement.sql',
      '0028': '0028_product_reviews.sql',
      '0029': '0029_auth_email_staff_accounts.sql',
      '0030': '0030_preorder_v1.sql',
      '0031': '0031_table_qr_guest_dinein.sql',
      '0032': '0032_auth_phone_first_password_reset.sql',
    };
    const filename = migrationFiles[ver];
    const fileSql = await readFile(path.join(migrationsDir, filename), 'utf8');
    const checksum = calculateChecksum(fileSql);
    await client.query(`INSERT INTO schema_migrations (version, name, checksum) VALUES ($1, $2, $3)`, [ver, filename, checksum]);
  }

  await client.query(`
    INSERT INTO stores (id, name) VALUES (1, 'Store 1'), (2, 'Store 2');
    INSERT INTO users (id, fullname, email, admin_role, admin_branch_id, is_active) VALUES
      (1, 'Customer One', 'customer@example.test', NULL, NULL, TRUE),
      (2, 'Manager One', 'manager1@example.test', 'manager', 1, TRUE),
      (3, 'Manager Two', 'manager2@example.test', 'manager', 2, TRUE),
      (9, 'Other Customer', 'other@example.test', NULL, NULL, TRUE);
  `);
}

describe('0033 Preorder Customer Check-in isolated rehearsal', () => {
  it('applies additively on post-0032, passes read-only preflight, and verifies snapshot consistency and resolution invariants', async (t) => {
    if (!enabled || !testDbUrl) return t.skip('Requires POSTGRES_INTEGRATION=1 and TEST_DATABASE_URL');

    const parsedUrl = new URL(testDbUrl);
    const guard = validatePostgresTestGuard(testDbUrl, {
      allowedHosts: parsedUrl.hostname,
      allowedProjectRefs: teaPlusTestProjectRef,
      productionProjectRefs: productionProjectRef,
    });
    assert.equal(guard.valid, true);

    const pool = new Pool({ ...getPostgresPoolConfig(testDbUrl), max: 1 });
    const client = await pool.connect();
    const schema = schemaName();

    try {
      await createPost0032Baseline(client, schema);

      // 1. Run Preflight before applying 0033
      const preflightSql = await readFile(preflightPath, 'utf8');
      const preflightResult = await client.query(preflightSql);
      for (const row of preflightResult.rows) {
        assert.equal(row.status, 'PASS', `Preflight check "${row.check_name}" must PASS (issue_count: ${row.issue_count})`);
        assert.equal(Number(row.issue_count), 0);
      }

      // 2. Apply Migration 0033 through canonical execution pattern
      const migrationSql = await readFile(migrationPath, 'utf8');
      const checksum = calculateChecksum(migrationSql);

      await client.query('BEGIN');
      try {
        await client.query(migrationSql);
        await client.query(
          `INSERT INTO schema_migrations (version, name, checksum) VALUES ($1, $2, $3)`,
          ['0033', '0033_preorder_customer_checkin.sql', checksum],
        );
        await client.query('COMMIT');
      } catch (err) {
        await client.query('ROLLBACK');
        throw err;
      }

      // Re-apply of idempotent SQL without duplicate tracker must succeed
      await client.query(migrationSql);

      // 3. Schema & Tables Verification
      const tables = await client.query(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = $1 AND table_name IN ('preorder_checkin_requests', 'preorder_slot_strike_events') ORDER BY table_name`,
        [schema],
      );
      assert.equal(tables.rows.length, 2);

      // 4. Test Check-in Flow and Invariants
      const slotStart = new Date('2026-09-14T15:00:00.000Z');
      const slotEnd = new Date('2026-09-14T16:00:00.000Z');

      const preorderRes = await client.query(
        `INSERT INTO preorders (preorder_code, store_id, customer_user_id, checkout_idempotency_key, scheduled_start_at, scheduled_end_at, status, responsible_manager_id)
         VALUES ('PO-CHECKIN-1', 1, 1, 'idem-key-1', $1, $2, 'CONFIRMED', 2)
         RETURNING id`,
        [slotStart, slotEnd],
      );
      const preorderId = preorderRes.rows[0].id;

      // Invariant: scheduled_end_at > scheduled_start_at
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
           VALUES ($1, 1, 1, $2, $3, 'PENDING')`,
          [preorderId, slotEnd, slotStart],
        ),
        /chk_preorder_checkin_schedule/,
      );

      // Invariant: Parent snapshot consistency via database trigger
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
           VALUES ($1, 2, 1, $2, $3, 'PENDING')`, // store_id mismatch
          [preorderId, slotStart, slotEnd],
        ),
        /preorder_checkin_requests\.store_id .* does not match parent preorder/,
      );

      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
           VALUES ($1, 1, 9, $2, $3, 'PENDING')`, // customer_user_id mismatch
          [preorderId, slotStart, slotEnd],
        ),
        /preorder_checkin_requests\.customer_user_id .* does not match parent preorder/,
      );

      // Invariant: Status consistency
      // PENDING cannot have resolved_by
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status, resolved_by, resolved_at)
           VALUES ($1, 1, 1, $2, $3, 'PENDING', 2, CURRENT_TIMESTAMP)`,
          [preorderId, slotStart, slotEnd],
        ),
        /chk_preorder_checkin_status_resolution/,
      );

      // CONFIRMED must have resolved_by and resolved_at
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
           VALUES ($1, 1, 1, $2, $3, 'CONFIRMED')`,
          [preorderId, slotStart, slotEnd],
        ),
        /chk_preorder_checkin_status_resolution/,
      );

      // REJECTED must have non-blank rejection_reason
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status, resolved_by, resolved_at, rejection_reason)
           VALUES ($1, 1, 1, $2, $3, 'REJECTED', 2, CURRENT_TIMESTAMP, '   ')`,
          [preorderId, slotStart, slotEnd],
        ),
        /chk_preorder_checkin_status_resolution/,
      );

      // Valid PENDING request insertion
      const checkinRes = await client.query(
        `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
         VALUES ($1, 1, 1, $2, $3, 'PENDING')
         RETURNING id`,
        [preorderId, slotStart, slotEnd],
      );
      assert.ok(checkinRes.rows[0].id);

      // Invariant: Unique request per (preorder_id, scheduled_start_at)
      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_checkin_requests (preorder_id, store_id, customer_user_id, scheduled_start_at, scheduled_end_at, status)
           VALUES ($1, 1, 1, $2, $3, 'PENDING')`,
          [preorderId, slotStart, slotEnd],
        ),
        /uq_preorder_checkin_slot/,
      );

      // Invariant: Strike idempotency (at most 1 per preorder_id, scheduled_start_at)
      await client.query(
        `INSERT INTO preorder_slot_strike_events (preorder_id, scheduled_start_at, manager_id, strike_source)
         VALUES ($1, $2, 2, 'CHECKIN_BREACH')`,
        [preorderId, slotStart],
      );

      await assert.rejects(
        () => client.query(
          `INSERT INTO preorder_slot_strike_events (preorder_id, scheduled_start_at, manager_id, strike_source)
           VALUES ($1, $2, 2, 'CONFIRMATION_BREACH')`,
          [preorderId, slotStart],
        ),
        /uq_preorder_slot_strike/,
      );
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      client.release();
      await pool.end();
    }
  });
});
