import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { getPostgresPoolConfig } from '../config/db-postgres.js';
import { validatePostgresTestGuard } from '../config/postgres-guard.js';
import { calculateChecksum } from '../database/postgres/migrate.js';
import { createPaymentAttemptsRepository, PaymentAttemptError } from '../repositories/postgres/payment-attempts.js';
import { createDirectPayOSAttemptService } from '../services/direct-payos-attempt.js';
import { createGroupedPayOSAttemptService } from '../services/grouped-payos-attempt.js';
import { processPayOSWebhookWithAttempts } from '../services/payment-attempt-settlement.js';
import { reconcilePayOSAttempt } from '../services/payos-reconciliation.js';

const { Pool } = pg;
const enabled = process.env.POSTGRES_INTEGRATION === '1';
const testDbUrl = process.env.TEST_DATABASE_URL;
const root = path.dirname(fileURLToPath(import.meta.url));
const migration0026 = path.join(root, '..', 'database', 'postgres', 'migrations', '0026_payment_attempts_additive.sql');
const migration0027 = path.join(root, '..', 'database', 'postgres', 'migrations', '0027_payment_attempts_enforcement.sql');
const preflight0027 = path.join(root, '..', 'database', 'postgres', 'verification', '0027_payment_attempts_preflight_readonly.sql');

function schemaName() {
  return `p1_rollout_${crypto.randomBytes(6).toString('hex')}`;
}

async function createPost0025Baseline(client, schema) {
  await client.query(`CREATE SCHEMA "${schema}"`);
  await client.query(`SET search_path TO "${schema}", public`);
  await client.query(`
    CREATE TABLE payment_profiles (code VARCHAR(50) PRIMARY KEY);
    CREATE TABLE checkout_groups (
      id BIGINT PRIMARY KEY, group_code VARCHAR(50), total_amount NUMERIC(15,2) NOT NULL,
      user_id BIGINT, payment_provider VARCHAR(30) NOT NULL DEFAULT 'payos', payment_status VARCHAR(30) NOT NULL,
      payment_profile_code VARCHAR(50) NOT NULL, payment_profile_version INT,
      payment_link_id VARCHAR(100), payos_order_code BIGINT, payment_checkout_url TEXT, payment_qr_code TEXT,
      payment_created_at TIMESTAMPTZ, payment_expires_at TIMESTAMPTZ, paid_at TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE orders (
      id BIGINT PRIMARY KEY, order_code VARCHAR(50), user_id BIGINT, cancel_token_hash VARCHAR(255), total NUMERIC(15,2) NOT NULL,
      checkout_group_id BIGINT, payment_provider VARCHAR(30), payment_status VARCHAR(20) NOT NULL, current_status VARCHAR(30),
      payment_profile_code VARCHAR(50), payment_profile_version INT, payment_link_id VARCHAR(100), payos_order_code BIGINT,
      payment_checkout_url TEXT, payment_qr_code TEXT, payment_created_at TIMESTAMPTZ, payment_expires_at TIMESTAMPTZ,
      paid_at TIMESTAMPTZ, transaction_id VARCHAR(255), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE payment_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider VARCHAR(50) NOT NULL,
      provider_event_key VARCHAR(255) NOT NULL UNIQUE, order_id BIGINT, event_type VARCHAR(100) NOT NULL,
      payload JSONB NOT NULL DEFAULT '{}'::jsonb, processing_status VARCHAR(50) NOT NULL DEFAULT 'pending',
      error_code VARCHAR(100), processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE schema_migrations (
      version VARCHAR(50) PRIMARY KEY, name VARCHAR(255) NOT NULL, checksum VARCHAR(64) NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO payment_profiles VALUES ('DIRECT_A'), ('GROUP_CHECKOUT');
    INSERT INTO checkout_groups (id, group_code, total_amount, user_id, payment_status, payment_profile_code, payment_profile_version)
    VALUES (10, 'GRP-ROLLOUT-10', 50000, 9, 'unpaid', 'GROUP_CHECKOUT', 1),
           (11, 'GRP-ROLLOUT-11', 51000, 9, 'unpaid', 'GROUP_CHECKOUT', 1);
    INSERT INTO orders (id, order_code, user_id, total, checkout_group_id, payment_provider, payment_status, current_status, payment_profile_code, payment_profile_version)
    VALUES (1, 'ORD-ROLLOUT-1', 9, 10000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (2, 'ORD-ROLLOUT-2', 9, 20000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (3, 'ORD-ROLLOUT-3', 9, 30000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (4, 'ORD-ROLLOUT-4', 9, 40000, NULL, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (5, 'ORD-ROLLOUT-5', 9, 50000, 10, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (6, 'ORD-ROLLOUT-6', 9, 25000, 10, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1),
           (7, 'ORD-ROLLOUT-7', 9, 51000, 11, 'payos', 'unpaid', 'pending', 'DIRECT_A', 1);
  `);
}

function database(client) {
  const query = async (sql, params = []) => {
    const result = await client.query(sql, params);
    return [result.rows, result.rowCount ?? 0];
  };
  return { query, transaction: async (runner) => runner({ query }) };
}

async function applyTrackedMigration(client, version, filename, sql) {
  await client.query('BEGIN');
  try {
    await client.query(sql);
    await client.query(
      'INSERT INTO schema_migrations (version, name, checksum) VALUES ($1, $2, $3)',
      [version, filename, calculateChecksum(sql)],
    );
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  }
}

function makePayOSHarness(prefix) {
  let sequence = 0;
  return {
    lookupPaymentLink: async () => ({ kind: 'not_found' }),
    createPaymentLink: async ({ payosOrderCode }) => {
      sequence += 1;
      return {
        paymentLinkId: `${prefix}-link-${sequence}`,
        checkoutUrl: `https://payos.test/${prefix}/${payosOrderCode}`,
        qrCode: `${prefix}-qr-${sequence}`,
      };
    },
  };
}

describe('Post-0025 staging P1 rollout rehearsal', () => {
  it('runs 0026 runtime smoke, zero-block preflight, then 0027 enforcement regression', async (t) => {
    if (!enabled || !testDbUrl) return t.skip('Requires POSTGRES_INTEGRATION=1 and TEST_DATABASE_URL');
    assert.equal(validatePostgresTestGuard(testDbUrl).valid, true);
    const [sql0026, sql0027, preflight] = await Promise.all([
      readFile(migration0026, 'utf8'), readFile(migration0027, 'utf8'), readFile(preflight0027, 'utf8'),
    ]);
    const pool = new Pool(getPostgresPoolConfig(testDbUrl));
    const client = await pool.connect();
    const schema = schemaName();
    try {
      await createPost0025Baseline(client, schema);
      await applyTrackedMigration(client, '0026', '0026_payment_attempts_additive.sql', sql0026);
      const repo = createPaymentAttemptsRepository(database(client));
      const now = () => new Date('2026-09-07T00:00:00.000Z');
      let code = 90100000000000;
      const directPayOS = makePayOSHarness('direct');
      const groupPayOS = makePayOSHarness('group');
      const direct = createDirectPayOSAttemptService({
        attemptsRepository: repo, ...directPayOS, now, makeProviderOrderCode: () => ++code,
        withCreationLock: async (_key, callback) => callback({ acquired: true }),
      });
      const group = createGroupedPayOSAttemptService({
        attemptsRepository: repo, ...groupPayOS, now, makeProviderOrderCode: () => ++code,
        groupsRepository: { findGroupByCode: async () => ({ id: 10, group_code: 'GRP-ROLLOUT-10', total_amount: 50000, user_id: 9, payment_status: 'unpaid', payment_profile_code: 'GROUP_CHECKOUT', payment_profile_version: 1 }) },
        withCreationLock: async (_key, callback) => callback({ acquired: true }),
      });

      // Runtime on 0026 only: direct and group create/regenerate retain legacy response fields.
      const directTarget = { id: 1, order_code: 'ORD-ROLLOUT-1', user_id: 9, total: 10000, payment_provider: 'payos', payment_status: 'unpaid', current_status: 'pending', payment_profile_code: 'DIRECT_A', payment_profile_version: 1, checkout_group_id: null };
      const directFirst = await direct.createForOrder({ order: directTarget, paymentProfile: { code: 'DIRECT_A', version: 1 } });
      assert.equal(directFirst.payment_link_id, 'direct-link-1');
      const directReplacement = await direct.regenerateForCustomer({ orderCode: 'ORD-ROLLOUT-1', userId: 9 });
      assert.equal(directReplacement.payment_link_id, 'direct-link-2');
      const groupTarget = { id: 10, group_code: 'GRP-ROLLOUT-10', total_amount: 50000, payment_provider: 'payos', payment_status: 'unpaid', payment_profile_code: 'GROUP_CHECKOUT', payment_profile_version: 1 };
      const groupFirst = await group.createForGroup({ group: groupTarget });
      assert.equal(groupFirst.payment_link_id, 'group-link-1');
      const groupReplacement = await group.regenerateForCustomer({ groupCode: 'GRP-ROLLOUT-10', userId: 9 });
      assert.equal(groupReplacement.payment_link_id, 'group-link-2');

      // Webhook settlement: an old superseded direct QR can still settle and wins atomically.
      const oldDirect = (await repo.findAttemptsByTarget({ orderId: 1 })).find((attempt) => attempt.status === 'superseded');
      const webhook = await processPayOSWebhookWithAttempts({
        body: { data: { orderCode: oldDirect.provider_order_code, paymentLinkId: oldDirect.provider_payment_link_id, amount: 10000, reference: 'webhook-direct-old', code: '00' } },
        attemptsRepository: repo,
        verifyWebhook: async (body, { profileCode }) => {
          assert.equal(profileCode, 'DIRECT_A');
          return body.data;
        },
      });
      assert.equal(webhook.kind, 'paid');
      const directAfterWebhook = await repo.findAttemptsByTarget({ orderId: 1 });
      assert.equal(directAfterWebhook.filter((attempt) => attempt.status === 'paid').length, 1);

      // Reconciliation settles the active direct target through the same event identity/lifecycle.
      const reconcileAttempt = await repo.reserveOrRecoverCreatingAttempt({ orderId: 2, paymentProfileCode: 'DIRECT_A', amount: 20000, providerOrderCode: ++code, expiresAt: '2026-09-07T00:15:00.000Z' });
      const activeForReconcile = await repo.activateAttempt({ attemptId: reconcileAttempt.attempt.id, providerOrderCode: reconcileAttempt.attempt.provider_order_code, paymentLinkId: 'recon-link', checkoutUrl: 'https://payos.test/recon', qrCode: 'recon-qr', expiresAt: '2026-09-07T00:15:00.000Z' });
      const reconciliation = await reconcilePayOSAttempt({
        attempt: activeForReconcile,
        attemptsRepository: repo,
        getPaymentInfo: async () => ({ status: 'PAID', amountPaid: 20000, id: 'recon-link', reference: 'recon-reference' }),
      });
      assert.equal(reconciliation.changed, true);

      // Expiry is idempotent for direct and group; valid late evidence still settles expired/group state.
      const expiringDirect = await repo.reserveOrRecoverCreatingAttempt({ orderId: 3, paymentProfileCode: 'DIRECT_A', amount: 30000, providerOrderCode: ++code, expiresAt: '2026-09-06T23:00:00.000Z' });
      await repo.activateAttempt({ attemptId: expiringDirect.attempt.id, providerOrderCode: expiringDirect.attempt.provider_order_code, paymentLinkId: 'expire-direct', checkoutUrl: 'https://payos.test/expire-direct', qrCode: 'expire-direct', expiresAt: '2026-09-06T23:00:00.000Z' });
      const expiringGroup = await repo.reserveOrRecoverCreatingAttempt({ checkoutGroupId: 11, paymentProfileCode: 'GROUP_CHECKOUT', amount: 51000, providerOrderCode: ++code, expiresAt: '2026-09-06T23:00:00.000Z' });
      await repo.activateAttempt({ attemptId: expiringGroup.attempt.id, providerOrderCode: expiringGroup.attempt.provider_order_code, paymentLinkId: 'expire-group', checkoutUrl: 'https://payos.test/expire-group', qrCode: 'expire-group', expiresAt: '2026-09-06T23:00:00.000Z' });
      const firstExpiry = await repo.expireDuePaymentAttempts({ now: '2026-09-07T00:00:00.000Z' });
      const rerunExpiry = await repo.expireDuePaymentAttempts({ now: '2026-09-07T00:00:00.000Z' });
      assert.equal(firstExpiry.expiredCount, 2);
      assert.equal(rerunExpiry.expiredCount, 0);
      const lateGroupPaid = await repo.processSuccessfulAttemptEvent({ attemptId: expiringGroup.attempt.id, provider: 'payos', providerPaymentIdentity: 'reference:late-group', amount: 51000, reference: 'late-group', paymentLinkId: 'expire-group' });
      assert.equal(lateGroupPaid.kind, 'paid');
      const [childAttempts] = await database(client).query('SELECT COUNT(*)::int AS count FROM payment_attempts WHERE order_id IN (5, 6)');
      assert.equal(childAttempts[0].count, 0);
      await assert.rejects(
        () => repo.reserveOrRecoverCreatingAttempt({ orderId: 5, paymentProfileCode: 'DIRECT_A', amount: 50000, providerOrderCode: ++code }),
        (error) => error instanceof PaymentAttemptError && error.code === 'GROUP_CHILD_DIRECT_ATTEMPT_FORBIDDEN',
      );

      // 0027 preflight must be clean before enforcement. No manual cleanup occurs.
      const preflightResult = await client.query(preflight);
      assert.equal(preflightResult.rows.every((row) => Number(row.issue_count) === 0 && row.status === 'PASS'), true, JSON.stringify(preflightResult.rows));
      await applyTrackedMigration(client, '0027', '0027_payment_attempts_enforcement.sql', sql0027);

      // Enforcement regression: constraints preserve P1 flows and reject child attempts/pointer misuse.
      const enforced = await repo.reserveOrRecoverCreatingAttempt({ orderId: 4, paymentProfileCode: 'DIRECT_A', amount: 40000, providerOrderCode: ++code, expiresAt: '2026-09-07T00:15:00.000Z' });
      const enforcedActive = await repo.activateAttempt({ attemptId: enforced.attempt.id, providerOrderCode: enforced.attempt.provider_order_code, paymentLinkId: 'enforced-link', checkoutUrl: 'https://payos.test/enforced', qrCode: 'enforced', expiresAt: '2026-09-07T00:15:00.000Z' });
      assert.equal(enforcedActive.status, 'active');
      await assert.rejects(
        () => client.query("INSERT INTO payment_attempts (target_type, order_id, provider, payment_profile_code, amount, status) VALUES ('order', 5, 'payos', 'DIRECT_A', 50000, 'creating')"),
        /grouped child|payment attempt order target/i,
      );
      const tracker = await client.query('SELECT version, name, checksum FROM schema_migrations WHERE version IN ($1, $2) ORDER BY version', ['0026', '0027']);
      assert.deepEqual(tracker.rows.map((row) => row.version), ['0026', '0027']);
      assert.equal(tracker.rows[0].checksum, calculateChecksum(sql0026));
      assert.equal(tracker.rows[1].checksum, calculateChecksum(sql0027));
      const invariantCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_constraint
        WHERE conname IN ('chk_payment_attempts_exactly_one_target', 'fk_orders_current_payment_attempt', 'fk_checkout_groups_current_payment_attempt')
      `);
      assert.equal(invariantCount.rows[0].count, 3);
      const indexCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_indexes
        WHERE indexname IN (
          'uq_payment_attempts_creating_order', 'uq_payment_attempts_creating_group',
          'uq_payment_attempts_provider_profile_order_code', 'uq_payment_attempts_provider_profile_link_id',
          'uq_payment_events_provider_profile_identity'
        )
      `);
      assert.equal(indexCount.rows[0].count, 5);
      const triggerCount = await client.query(`
        SELECT COUNT(*)::int AS count FROM pg_trigger
        WHERE NOT tgisinternal AND tgname IN (
          'trg_payment_attempt_target_0027', 'trg_payment_attempt_immutable_0027',
          'trg_order_current_attempt_0027', 'trg_checkout_group_current_attempt_0027'
        )
      `);
      assert.equal(triggerCount.rows[0].count, 4);
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      client.release();
      await pool.end();
    }
  });
});
