import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { getPostgresPoolConfig } from '../config/db-postgres.js';
import { validatePostgresTestGuard } from '../config/postgres-guard.js';

const { Pool } = pg;
const testDbUrl = process.env.TEST_DATABASE_URL;
const enabled = process.env.POSTGRES_INTEGRATION === '1';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const migrationPath = path.join(root, 'database', 'postgres', 'migrations', '0030_preorder_v1.sql');
const teaPlusTestProjectRef = 'sumodxrhsbnirvrvnwpy';
const productionProjectRef = 'duahwveccxdtueweyfov';

function schemaName() { return `preorder_0030_${crypto.randomBytes(6).toString('hex')}`; }

async function createPost0029Baseline(client, schema) {
  await client.query(`CREATE SCHEMA "${schema}"`);
  await client.query(`SET search_path TO "${schema}", public`);
  await client.query(`
    CREATE TABLE users (
      id BIGINT PRIMARY KEY, fullname TEXT NOT NULL, email TEXT,
      admin_role VARCHAR(40), admin_branch_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE,
      token_version INTEGER NOT NULL DEFAULT 1
    );
    CREATE TABLE stores (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE tables (id BIGINT PRIMARY KEY, store_id BIGINT NOT NULL REFERENCES stores(id), name TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE);
    CREATE TABLE checkout_groups (id BIGINT PRIMARY KEY);
    CREATE TABLE promotions (id BIGINT PRIMARY KEY, code TEXT NOT NULL);
    CREATE TABLE orders (
      id BIGINT PRIMARY KEY, store_id BIGINT NOT NULL REFERENCES stores(id), user_id BIGINT REFERENCES users(id),
      checkout_group_id BIGINT REFERENCES checkout_groups(id), current_payment_attempt_id BIGINT
    );
    CREATE TABLE order_status_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id BIGINT REFERENCES orders(id), status VARCHAR(50) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE order_items (id BIGINT PRIMARY KEY, order_id BIGINT REFERENCES orders(id));
  `);
  await client.query(`
    INSERT INTO stores (id,name) VALUES (1,'Store One'),(2,'Store Two');
    INSERT INTO users (id,fullname,email,admin_role,admin_branch_id,is_active) VALUES
      (1,'Customer','customer@example.test',NULL,NULL,TRUE),
      (2,'Manager One','manager@example.test','manager',1,TRUE),
      (3,'Manager Two','manager2@example.test','manager',2,TRUE),
      (4,'Inactive Manager','inactive@example.test','manager',1,FALSE),
      (5,'Super','super@example.test','super',NULL,TRUE);
    INSERT INTO tables (id,store_id,name) VALUES (10,1,'A1'),(20,2,'B1');
    INSERT INTO checkout_groups (id) VALUES (101),(102);
    INSERT INTO promotions (id,code) VALUES (1,'PREORDER');
  `);
}

describe('0030 Preorder migration isolated rehearsal', () => {
  it('applies additively on a post-0029 fixture, protects table overlap, and preserves the locked state model', async (t) => {
    if (!enabled || !testDbUrl) return t.skip('Requires POSTGRES_INTEGRATION=1 and TEST_DATABASE_URL');
    // TeaPlus-Test deliberately uses the Supabase pooler database name
    // "postgres". Keep the production guard strict, but give this isolated
    // integration harness an explicit, test-only target allowlist.
    const parsedUrl = new URL(testDbUrl);
    const guard = validatePostgresTestGuard(testDbUrl, {
      allowedHosts: parsedUrl.hostname,
      allowedProjectRefs: teaPlusTestProjectRef,
      productionProjectRefs: productionProjectRef,
    });
    assert.equal(guard.valid, true);
    assert.equal(guard.projectRef, teaPlusTestProjectRef);
    const pool = new Pool({ ...getPostgresPoolConfig(testDbUrl), max: 1 });
    const client = await pool.connect();
    const schema = schemaName();
    try {
      await createPost0029Baseline(client, schema);
      // With the generated schema first in search_path, 0030 creates the
      // extension into that disposable context when necessary. Dropping this
      // schema in finally removes it too; public is never reset or mutated.
      const sql = await readFile(migrationPath, 'utf8');
      await client.query(sql);
      await client.query(sql);

      const tables = await client.query(`SELECT table_name FROM information_schema.tables WHERE table_schema = $1 AND table_name IN ('preorders','preorder_store_settings','preorder_table_reservations','preorder_reschedule_history','preorder_confirmation_incidents','manager_preorder_strikes','preorder_notification_deliveries') ORDER BY table_name`, [schema]);
      assert.equal(tables.rows.length, 7);
      const promotion = await client.query('SELECT applies_to_preorder FROM promotions WHERE id = 1');
      assert.equal(promotion.rows[0].applies_to_preorder, false);

      await client.query(`INSERT INTO preorder_store_settings (store_id,is_enabled,responsible_manager_id) VALUES (1,TRUE,2)`);
      await assert.rejects(
        () => client.query(`INSERT INTO preorder_store_settings (store_id,is_enabled,responsible_manager_id) VALUES (2,TRUE,2)`),
        /responsible manager must be active manager of the same store/i,
      );
      const pre = await client.query(`INSERT INTO preorders (preorder_code,store_id,customer_user_id,checkout_idempotency_key,scheduled_start_at,scheduled_end_at,status,responsible_manager_id) VALUES ('PO-1',1,1,'key-1','2026-09-12T11:00:00Z','2026-09-12T12:00:00Z','AWAITING_PAYMENT',2) RETURNING id`);
      await client.query(`INSERT INTO orders (id,store_id,user_id,checkout_group_id,preorder_id) VALUES (500,1,1,101,$1)`, [pre.rows[0].id]);
      await assert.rejects(
        () => client.query(`UPDATE preorders SET checkout_group_id = 102 WHERE id = $1`, [pre.rows[0].id]),
        /preorder checkout group must match every linked service order/i,
      );
      await client.query(`UPDATE preorders SET checkout_group_id = 101 WHERE id = $1`, [pre.rows[0].id]);
      await client.query(`INSERT INTO preorder_table_reservations (preorder_id,table_id,reserved_from,reserved_until,status) VALUES ($1,10,'2026-09-12T10:30:00Z','2026-09-12T12:00:00Z','pending_payment')`, [pre.rows[0].id]);
      const pre2 = await client.query(`INSERT INTO preorders (preorder_code,store_id,customer_user_id,checkout_idempotency_key,scheduled_start_at,scheduled_end_at,status,responsible_manager_id) VALUES ('PO-2',1,1,'key-2','2026-09-12T11:30:00Z','2026-09-12T12:30:00Z','AWAITING_PAYMENT',2) RETURNING id`);
      await assert.rejects(
        () => client.query(`INSERT INTO preorder_table_reservations (preorder_id,table_id,reserved_from,reserved_until,status) VALUES ($1,10,'2026-09-12T11:00:00Z','2026-09-12T12:30:00Z','pending_payment')`, [pre2.rows[0].id]),
        /ex_preorder_table_reservations_active|conflicting key value/i,
      );
      const constraint = await client.query(`SELECT 1 FROM pg_constraint WHERE conname = 'ex_preorder_table_reservations_active' AND conrelid = 'preorder_table_reservations'::regclass`);
      assert.equal(constraint.rows.length, 1);
      const statuses = await client.query(`SELECT pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname = 'preorders_status_check'`);
      assert.equal(statuses.rows.length, 1);
      assert.equal(statuses.rows[0].definition.includes('MANAGER_RESCHEDULED'), false);
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      client.release();
      await pool.end();
    }
  });
});
