import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { Pool } from 'pg';
import { validatePostgresTestGuard } from '../config/postgres-guard.js';

const isPostgresIntegration = process.env.POSTGRES_INTEGRATION === '1';
const testDbUrl = process.env.TEST_DATABASE_URL || process.env.DATABASE_URL;

describe('PostgreSQL Adapter & Transaction Integration Suite', () => {
  it('executes parameterized queries, transactions, and rollbacks on live PostgreSQL', async (t) => {
    if (!isPostgresIntegration || !testDbUrl) {
      t.skip('Skipping live PostgreSQL integration: Requires POSTGRES_INTEGRATION=1 and TEST_DATABASE_URL pointing to dedicated test DB');
      return;
    }

    // 1. Guard check
    const guard = validatePostgresTestGuard(testDbUrl);
    assert.equal(guard.valid, true);

    const pool = new Pool({ connectionString: testDbUrl });

    try {
      // 2. Simple Parameterized Query Test
      const queryRes = await pool.query('SELECT $1::int as test_val, $2::text as test_text', [42, 'teaplus']);
      assert.equal(queryRes.rows.length, 1);
      assert.equal(queryRes.rows[0].test_val, 42);
      assert.equal(queryRes.rows[0].test_text, 'teaplus');

      // 3. Setup temporary table for transaction tests
      await pool.query(`
        CREATE TEMPORARY TABLE temp_test_adapter (
          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        ) ON COMMIT PRESERVE ROWS;
      `);

      // 4. Transaction Commit Test
      const client1 = await pool.connect();
      try {
        await client1.query('BEGIN');
        await client1.query('INSERT INTO temp_test_adapter (name) VALUES ($1)', ['committed_row']);
        await client1.query('COMMIT');
      } finally {
        client1.release();
      }

      const commitCheck = await pool.query('SELECT * FROM temp_test_adapter WHERE name = $1', ['committed_row']);
      assert.equal(commitCheck.rows.length, 1);

      // 5. Transaction Rollback Test
      const client2 = await pool.connect();
      try {
        await client2.query('BEGIN');
        await client2.query('INSERT INTO temp_test_adapter (name) VALUES ($1)', ['rolled_back_row']);
        await client2.query('ROLLBACK');
      } finally {
        client2.release();
      }

      const rollbackCheck = await pool.query('SELECT * FROM temp_test_adapter WHERE name = $1', ['rolled_back_row']);
      assert.equal(rollbackCheck.rows.length, 0, 'Rolled back row must not exist');
    } finally {
      await pool.end();
    }
  });
});
