-- PostgreSQL baseline that preserves the active SQL Server application contract.
-- Do not rename application columns here: route conversion happens in checkpoint C.

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL,
    lat NUMERIC(10,7),
    lng NUMERIC(10,7),
    hours VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    amenities TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    password_hash VARCHAR(255),
    avatar_url VARCHAR(500),
    address VARCHAR(300),
    tier VARCHAR(20) NOT NULL DEFAULT 'Đồng' CHECK (tier IN ('Đồng', 'Bạc', 'Vàng', 'Kim Cương')),
    points INTEGER NOT NULL DEFAULT 0,
    total_spent BIGINT NOT NULL DEFAULT 0,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    admin_role VARCHAR(20) CHECK (admin_role IN ('super', 'manager', 'kitchen', 'cashier')),
    admin_branch_id BIGINT REFERENCES stores(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_users_admin_identity CHECK (
      (is_admin = FALSE AND admin_role IS NULL AND admin_branch_id IS NULL)
      OR (is_admin = TRUE AND admin_role IS NOT NULL)
    )
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    slug VARCHAR(150) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    base_tea VARCHAR(100) NOT NULL,
    description TEXT,
    price INTEGER NOT NULL CHECK (price >= 0),
    image_url TEXT,
    rating NUMERIC(2,1) NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    review_count INTEGER NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    calories INTEGER NOT NULL DEFAULT 0 CHECK (calories >= 0),
    fruit_group VARCHAR(100),
    tags TEXT,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE size_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price_extra INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE base_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE sugar_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(50) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE ice_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(50) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    qr_code_token VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    type VARCHAR(100) NOT NULL,
    code VARCHAR(50),
    description TEXT,
    rule TEXT,
    emoji VARCHAR(10),
    discount_value INTEGER,
    discount_type VARCHAR(20) CHECK (discount_type IN ('percent', 'fixed')),
    voucher_type VARCHAR(30) NOT NULL DEFAULT 'time_bounded' CHECK (voucher_type IN ('single_use', 'time_bounded')),
    usage_limit INTEGER,
    used_count INTEGER NOT NULL DEFAULT 0,
    max_discount INTEGER,
    min_order INTEGER,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Lên lịch' CHECK (status IN ('Sắp diễn ra', 'Đang diễn ra', 'Đã kết thúc', 'Lên lịch', 'Đang chạy', 'Kết thúc')),
    audience VARCHAR(200),
    scope VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_promotions_dates CHECK (start_date <= end_date)
);
CREATE UNIQUE INDEX uq_promotions_code ON promotions(code) WHERE code IS NOT NULL;

CREATE TABLE promotion_stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotions(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    UNIQUE (promotion_id, store_id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(20) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    table_id BIGINT REFERENCES tables(id),
    location_name VARCHAR(200),
    order_type VARCHAR(20) NOT NULL DEFAULT 'Take-away' CHECK (order_type IN ('Delivery', 'Take-away', 'POS')),
    payment_method VARCHAR(20) NOT NULL DEFAULT 'COD' CHECK (payment_method IN ('COD', 'VietQR', 'MoMo', 'ZaloPay')),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'paid', 'expired')),
    payment_provider VARCHAR(30),
    payment_link_id VARCHAR(100),
    payos_order_code BIGINT,
    transaction_id VARCHAR(100),
    payment_created_at TIMESTAMPTZ,
    payment_expires_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    paid_verified_by BIGINT,
    customer_name VARCHAR(120) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    delivery_addr VARCHAR(300),
    voucher_code VARCHAR(50),
    discount_amount INTEGER NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    points_used INTEGER NOT NULL DEFAULT 0 CHECK (points_used >= 0),
    points_earned INTEGER NOT NULL DEFAULT 0 CHECK (points_earned >= 0),
    subtotal INTEGER NOT NULL CHECK (subtotal >= 0),
    total INTEGER NOT NULL CHECK (total >= 0),
    shipping_driver_name VARCHAR(120),
    shipping_driver_phone VARCHAR(20),
    shipping_tracking_url VARCHAR(500),
    cancel_token_hash CHAR(64),
    is_printed BOOLEAN NOT NULL DEFAULT FALSE,
    kitchen_notified_at TIMESTAMPTZ,
    note VARCHAR(500),
    cancel_reason VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_orders_discount_subtotal CHECK (discount_amount <= subtotal)
);

CREATE TABLE voucher_usage_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotions(id),
    user_phone VARCHAR(20) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name VARCHAR(200) NOT NULL,
    qty INTEGER NOT NULL DEFAULT 1 CHECK (qty > 0),
    size_label VARCHAR(50) NOT NULL,
    base_tea VARCHAR(100) NOT NULL,
    sugar_level VARCHAR(50) NOT NULL,
    ice_level VARCHAR(50) NOT NULL,
    note VARCHAR(300),
    unit_price INTEGER NOT NULL CHECK (unit_price >= 0),
    line_total INTEGER NOT NULL CHECK (line_total >= 0)
);
CREATE TABLE order_item_toppings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    topping_name VARCHAR(150) NOT NULL,
    topping_price INTEGER NOT NULL CHECK (topping_price >= 0)
);
CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL CHECK (status IN ('Chờ xác nhận', 'Đã xác nhận', 'Đang chuẩn bị', 'Đang giao', 'Hoàn thành', 'Đã hủy')),
    note VARCHAR(300),
    changed_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    order_item_id BIGINT REFERENCES order_items(id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    image_urls TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review UNIQUE (user_id, product_id, order_item_id)
);
CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wishlist UNIQUE (user_id, product_id)
);
CREATE TABLE rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    emoji VARCHAR(10),
    points_cost INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('voucher', 'topping', 'upsize', 'product', 'merchandise')),
    value INTEGER,
    stock INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('earn', 'redeem', 'expire', 'admin')),
    source VARCHAR(200),
    note VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    promotion_id BIGINT REFERENCES promotions(id),
    code VARCHAR(50) NOT NULL,
    used_at TIMESTAMPTZ,
    expires_at DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(100) NOT NULL,
    salary VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT NOT NULL,
    benefits TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE job_stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    UNIQUE (job_id, store_id)
);
CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id),
    store_id BIGINT REFERENCES stores(id),
    fullname VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    cv_url VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'Mới' CHECK (status IN ('Mới', 'Đang xem xét', 'Phỏng vấn', 'Trúng tuyển', 'Từ chối')),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    kind VARCHAR(20) NOT NULL DEFAULT 'fresh' CHECK (kind IN ('fresh', 'canned', 'dry', 'other')),
    unit VARCHAR(20) NOT NULL,
    stock NUMERIC(10,2) NOT NULL DEFAULT 0,
    safe_level NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ingredient_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    change_amount NUMERIC(10,2) NOT NULL,
    reason VARCHAR(200) NOT NULL,
    reference VARCHAR(200),
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('order', 'voucher', 'news', 'stock', 'staff', 'payment', 'system')),
    title VARCHAR(300) NOT NULL,
    body TEXT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    link VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    action VARCHAR(200) NOT NULL,
    detail TEXT,
    ip_address VARCHAR(45),
    user_agent VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE tier_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier VARCHAR(20) NOT NULL UNIQUE CHECK (tier IN ('Đồng', 'Bạc', 'Vàng', 'Kim Cương')),
    min_points INTEGER NOT NULL DEFAULT 0,
    discount_percent INTEGER NOT NULL DEFAULT 0,
    freeship_km NUMERIC(5,1),
    birthday_gift VARCHAR(200),
    description TEXT
);
