-- ==========================================================
-- Migration 0011_catalog_v2_foundation.sql
-- Catalog V2: Multi-Category Tree, Dynamic Product Schemas,
-- Product Variants, Modifiers, Media, and Packing Role
-- ==========================================================

-- 1. Extend users admin_role check constraint to include 'packing'
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_admin_role_check;
ALTER TABLE users ADD CONSTRAINT users_admin_role_check
    CHECK (admin_role IN ('super', 'manager', 'kitchen', 'cashier', 'packing'));

-- 2. Extend categories with tree hierarchy and product type association
ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS depth INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS product_type_id BIGINT,
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

ALTER TABLE categories DROP CONSTRAINT IF EXISTS chk_categories_depth;
ALTER TABLE categories ADD CONSTRAINT chk_categories_depth
    CHECK (depth BETWEEN 0 AND 2);

-- 3. Product Types
CREATE TABLE IF NOT EXISTS product_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    default_stock_mode VARCHAR(50) NOT NULL DEFAULT 'made_to_order'
        CHECK (default_stock_mode IN ('tracked', 'made_to_order')),
    default_fulfillment_lane VARCHAR(50) NOT NULL DEFAULT 'kitchen'
        CHECK (default_fulfillment_lane IN ('kitchen', 'packing')),
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key linking categories to product_types
ALTER TABLE categories DROP CONSTRAINT IF EXISTS fk_categories_product_type;
ALTER TABLE categories ADD CONSTRAINT fk_categories_product_type
    FOREIGN KEY (product_type_id) REFERENCES product_types(id) ON DELETE SET NULL;

-- 4. Product Type Schemas (Immutable Versioning)
CREATE TABLE IF NOT EXISTS product_type_schemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id BIGINT NOT NULL REFERENCES product_types(id) ON DELETE CASCADE,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    status VARCHAR(50) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'published', 'retired')),
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_type_version UNIQUE (product_type_id, version)
);

-- 5. Attribute Definitions (Variants and Modifiers)
CREATE TABLE IF NOT EXISTS attribute_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_id BIGINT NOT NULL REFERENCES product_type_schemas(id) ON DELETE CASCADE,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('variant', 'modifier')),
    input_type VARCHAR(50) NOT NULL CHECK (input_type IN ('single_select', 'multi_select', 'text', 'number')),
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_filterable BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    min_selections INTEGER DEFAULT 0,
    max_selections INTEGER,
    validation_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schema_attribute_code UNIQUE (schema_id, code)
);

-- 6. Attribute Values
CREATE TABLE IF NOT EXISTS attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE CASCADE,
    code VARCHAR(100) NOT NULL,
    label VARCHAR(200) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    price_adjustment INTEGER NOT NULL DEFAULT 0 CHECK (price_adjustment >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attribute_value_code UNIQUE (attribute_definition_id, code)
);

-- 7. Extend products with V2 schema and fulfillment properties
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS product_type_schema_id BIGINT REFERENCES product_type_schemas(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS fulfillment_lane VARCHAR(50) NOT NULL DEFAULT 'kitchen',
    ADD COLUMN IF NOT EXISTS stock_mode VARCHAR(50) NOT NULL DEFAULT 'made_to_order';

ALTER TABLE products DROP CONSTRAINT IF EXISTS chk_products_status;
ALTER TABLE products ADD CONSTRAINT chk_products_status
    CHECK (status IN ('draft', 'active', 'archived'));

ALTER TABLE products DROP CONSTRAINT IF EXISTS chk_products_fulfillment_lane;
ALTER TABLE products ADD CONSTRAINT chk_products_fulfillment_lane
    CHECK (fulfillment_lane IN ('kitchen', 'packing'));

ALTER TABLE products DROP CONSTRAINT IF EXISTS chk_products_stock_mode;
ALTER TABLE products ADD CONSTRAINT chk_products_stock_mode
    CHECK (stock_mode IN ('tracked', 'made_to_order'));

-- 8. Product Variants (SKUs)
CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    sku VARCHAR(100) NOT NULL UNIQUE,
    variant_signature VARCHAR(255) NOT NULL,
    name_suffix VARCHAR(200),
    barcode VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_variant_signature UNIQUE (product_id, variant_signature)
);

-- 9. Product Variant Values (Mapping variants to attribute values)
CREATE TABLE IF NOT EXISTS product_variant_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE RESTRICT,
    attribute_value_id BIGINT NOT NULL REFERENCES attribute_values(id) ON DELETE RESTRICT,
    CONSTRAINT uq_variant_attribute UNIQUE (variant_id, attribute_definition_id)
);

-- 10. Product Modifier Values (Mapping products to available modifier values with optional overrides)
CREATE TABLE IF NOT EXISTS product_modifier_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE RESTRICT,
    attribute_value_id BIGINT NOT NULL REFERENCES attribute_values(id) ON DELETE RESTRICT,
    price_override INTEGER CHECK (price_override IS NULL OR price_override >= 0),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_product_modifier_value UNIQUE (product_id, attribute_definition_id, attribute_value_id)
);

-- 11. Product Media (Multiple Images Support)
CREATE TABLE IF NOT EXISTS product_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 12. Supporting Indexes for High-Performance Queries
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_depth ON categories(depth);
CREATE INDEX IF NOT EXISTS idx_product_types_code ON product_types(code);
CREATE INDEX IF NOT EXISTS idx_product_type_schemas_type_id ON product_type_schemas(product_type_id);
CREATE INDEX IF NOT EXISTS idx_attribute_definitions_schema_id ON attribute_definitions(schema_id);
CREATE INDEX IF NOT EXISTS idx_attribute_values_def_id ON attribute_values(attribute_definition_id);
CREATE INDEX IF NOT EXISTS idx_products_schema_id ON products(product_type_schema_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_sku ON product_variants(sku);
CREATE INDEX IF NOT EXISTS idx_product_media_product_id ON product_media(product_id);
