-- ==========================================================
-- Migration 0012_branch_offers_inventory.sql
-- Catalog V2: Branch Variant Offers, Tracked SKU Inventory,
-- Append-Only Inventory Ledger & Reservations
-- ==========================================================

-- 1. Branch Variant Offers (Branch pricing & SKU availability)
CREATE TABLE IF NOT EXISTS branch_variant_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    price INTEGER NOT NULL CHECK (price >= 0),
    compare_at_price INTEGER CHECK (compare_at_price IS NULL OR compare_at_price >= 0),
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_branch_variant_offer UNIQUE (store_id, variant_id)
);

-- 2. Branch Variant Inventory (Optimistic concurrency on-hand & reserved)
CREATE TABLE IF NOT EXISTS branch_variant_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    on_hand INTEGER NOT NULL DEFAULT 0 CHECK (on_hand >= 0),
    reserved INTEGER NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_branch_variant_inventory UNIQUE (store_id, variant_id),
    CONSTRAINT chk_inventory_reserved_le_on_hand CHECK (reserved <= on_hand)
);

-- 3. Inventory Movements (Append-only immutable audit ledger)
CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    movement_type VARCHAR(50) NOT NULL
        CHECK (movement_type IN ('receive', 'adjust', 'reserve', 'release', 'sale', 'cancel_restock', 'return_restock')),
    quantity INTEGER NOT NULL,
    before_on_hand INTEGER NOT NULL CHECK (before_on_hand >= 0),
    after_on_hand INTEGER NOT NULL CHECK (after_on_hand >= 0),
    before_reserved INTEGER NOT NULL DEFAULT 0 CHECK (before_reserved >= 0),
    after_reserved INTEGER NOT NULL DEFAULT 0 CHECK (after_reserved >= 0),
    reference_type VARCHAR(50),
    reference_id VARCHAR(100),
    reason TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Inventory Reservations (Temporary hold during checkout / payment)
CREATE TABLE IF NOT EXISTS inventory_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_group_id VARCHAR(100),
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    order_item_id BIGINT,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    status VARCHAR(50) NOT NULL DEFAULT 'reserved'
        CHECK (status IN ('reserved', 'committed', 'released', 'expired')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Supporting Indexes
CREATE INDEX IF NOT EXISTS idx_branch_offers_store_variant ON branch_variant_offers(store_id, variant_id);
CREATE INDEX IF NOT EXISTS idx_branch_inventory_store_variant ON branch_variant_inventory(store_id, variant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_store_variant ON inventory_movements(store_id, variant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_reservations_status_expires ON inventory_reservations(status, expires_at);
