-- ==========================================================
-- Migration 0014_fulfillment_lanes.sql
-- Fulfillment Kitchen / Packing Task Splitting & Lane Management
-- ==========================================================

CREATE TABLE IF NOT EXISTS fulfillment_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    branch_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    lane VARCHAR(50) NOT NULL CHECK (lane IN ('kitchen', 'packing')),
    status VARCHAR(50) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'preparing', 'ready', 'completed', 'cancelled')),
    assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fulfillment_order_lane UNIQUE (order_id, lane)
);

CREATE INDEX IF NOT EXISTS idx_fulfillment_tasks_branch_lane_status
    ON fulfillment_tasks (branch_id, lane, status);

CREATE INDEX IF NOT EXISTS idx_fulfillment_tasks_order_id
    ON fulfillment_tasks (order_id);

CREATE TABLE IF NOT EXISTS fulfillment_task_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES fulfillment_tasks(id) ON DELETE CASCADE,
    order_item_id BIGINT REFERENCES order_items(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    variant_id BIGINT REFERENCES product_variants(id) ON DELETE SET NULL,
    sku VARCHAR(100),
    product_name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    modifiers_snapshot JSONB,
    item_notes VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fulfillment_task_items_task_id
    ON fulfillment_task_items (task_id);
