-- ==========================================================
-- Migration 0015_root_category_navigation.sql
-- Audit table for Category Reparenting and Root Navigation Rollback
-- ==========================================================

CREATE TABLE IF NOT EXISTS catalog_category_reparent_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key VARCHAR(100) NOT NULL,
    root_category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    old_parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    old_depth INTEGER NOT NULL,
    root_was_created BOOLEAN NOT NULL DEFAULT FALSE,
    moved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reparent_run_category UNIQUE (run_key, category_id)
);

CREATE INDEX IF NOT EXISTS idx_reparent_history_run_key
    ON catalog_category_reparent_history (run_key);
