-- ==========================================================
-- Migration 0016_catalog_option_scopes.sql
-- Category Slug Aliases, Dynamic Category Attribute Assignments & Product Overrides
-- ==========================================================

-- 1. Category Slug Aliases (Allows legacy or alias slugs e.g. 'thuc-don' -> 'nuoc-uong')
CREATE TABLE IF NOT EXISTS category_slug_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_slug VARCHAR(150) NOT NULL UNIQUE,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_category_slug_alias_normalized
        CHECK (alias_slug = LOWER(BTRIM(alias_slug)) AND alias_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE INDEX IF NOT EXISTS idx_category_slug_aliases_category_id
    ON category_slug_aliases (category_id);

-- 2. Category Attribute Assignments (Assigning option groups to categories with inheritance)
CREATE TABLE IF NOT EXISTS category_attribute_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE CASCADE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    inherit_to_descendants BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_required BOOLEAN,
    min_selected INTEGER,
    max_selected INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_category_attribute_assignment UNIQUE (category_id, attribute_definition_id),
    CONSTRAINT chk_category_attribute_selection_bounds CHECK (
        (min_selected IS NULL OR min_selected >= 0)
        AND (max_selected IS NULL OR max_selected >= 0)
        AND (min_selected IS NULL OR max_selected IS NULL OR min_selected <= max_selected)
    )
);

CREATE INDEX IF NOT EXISTS idx_cat_attr_assign_category_id
    ON category_attribute_assignments (category_id);

CREATE INDEX IF NOT EXISTS idx_cat_attr_assign_attribute_def_id
    ON category_attribute_assignments (attribute_definition_id);

-- 3. Product Attribute Overrides (Product-level explicit option override e.g. disable sugar on bottled tea)
CREATE TABLE IF NOT EXISTS product_attribute_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE CASCADE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    is_required BOOLEAN,
    min_selected INTEGER,
    max_selected INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_attribute_override UNIQUE (product_id, attribute_definition_id),
    CONSTRAINT chk_product_attribute_selection_bounds CHECK (
        (min_selected IS NULL OR min_selected >= 0)
        AND (max_selected IS NULL OR max_selected >= 0)
        AND (min_selected IS NULL OR max_selected IS NULL OR min_selected <= max_selected)
    )
);

CREATE INDEX IF NOT EXISTS idx_prod_attr_override_product_id
    ON product_attribute_overrides (product_id);

CREATE INDEX IF NOT EXISTS idx_prod_attr_override_attribute_def_id
    ON product_attribute_overrides (attribute_definition_id);
