-- ==========================================================
-- Migration 0017_fulfillment_capabilities.sql
-- Fulfillment Lane Registry, Branch Capabilities & Hardened Task References
-- ==========================================================

-- 1. Fulfillment Lane Registry (System & Dynamic Handlers)
CREATE TABLE IF NOT EXISTS fulfillment_lane_registry (
    code VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    handler_type VARCHAR(50) NOT NULL DEFAULT 'standard',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed baseline lanes
INSERT INTO fulfillment_lane_registry (code, display_name, handler_type, is_active, is_system)
VALUES 
    ('kitchen', 'Pha chế / Bếp', 'kitchen', TRUE, TRUE),
    ('packing', 'Soạn hàng / Đóng gói', 'packing', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- 2. Branch Fulfillment Capabilities (Which branches can fulfill which lanes)
CREATE TABLE IF NOT EXISTS branch_fulfillment_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    lane_code VARCHAR(50) NOT NULL REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_branch_fulfillment_lane UNIQUE (store_id, lane_code)
);

CREATE INDEX IF NOT EXISTS idx_branch_capabilities_store_id
    ON branch_fulfillment_capabilities (store_id);

-- 3. Categories: default_fulfillment_lane
ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS default_fulfillment_lane VARCHAR(50)
    REFERENCES fulfillment_lane_registry(code) ON DELETE SET NULL;

-- 4. Products: fulfillment_lane becomes nullable explicit override
ALTER TABLE products
    ALTER COLUMN fulfillment_lane DROP DEFAULT;

ALTER TABLE products
    ALTER COLUMN fulfillment_lane DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_products_fulfillment_lane'
    ) THEN
        ALTER TABLE products
            ADD CONSTRAINT fk_products_fulfillment_lane
            FOREIGN KEY (fulfillment_lane)
            REFERENCES fulfillment_lane_registry(code) ON DELETE SET NULL;
    END IF;
END $$;

-- 5. Order Items: snapshot fulfillment_lane
ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS fulfillment_lane VARCHAR(50)
    REFERENCES fulfillment_lane_registry(code) ON DELETE SET NULL;

-- 6. Fulfillment Tasks & Items hardening
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fulfillment_tasks_lane_check'
    ) THEN
        ALTER TABLE fulfillment_tasks DROP CONSTRAINT fulfillment_tasks_lane_check;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_fulfillment_tasks_lane'
    ) THEN
        ALTER TABLE fulfillment_tasks
            ADD CONSTRAINT fk_fulfillment_tasks_lane
            FOREIGN KEY (lane)
            REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fulfillment_task_order_item
    ON fulfillment_task_items (task_id, order_item_id)
    WHERE order_item_id IS NOT NULL;
