-- ==========================================================
-- Migration 0017_fulfillment_capabilities.sql
-- Fulfillment Lane Registry, Branch Capabilities & Hardened Task References
-- ==========================================================

-- 1. Fulfillment Lane Registry (only system handlers are supported in this phase)
CREATE TABLE IF NOT EXISTS fulfillment_lane_registry (
    code VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    handler_type VARCHAR(50) NOT NULL DEFAULT 'standard',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_fulfillment_lane_code CHECK (code = LOWER(BTRIM(code)) AND code ~ '^[a-z][a-z0-9_-]*$'),
    CONSTRAINT chk_fulfillment_handler_type CHECK (handler_type IN ('kitchen', 'packing'))
);

-- Older development databases may already have this table with the temporary
-- handler_type='standard' default. Normalize it before enforcing the v2 contract.
UPDATE fulfillment_lane_registry
SET handler_type = CASE WHEN code = 'packing' THEN 'packing' ELSE 'kitchen' END
WHERE handler_type NOT IN ('kitchen', 'packing');

ALTER TABLE fulfillment_lane_registry DROP CONSTRAINT IF EXISTS chk_fulfillment_handler_type;
ALTER TABLE fulfillment_lane_registry ADD CONSTRAINT chk_fulfillment_handler_type
    CHECK (handler_type IN ('kitchen', 'packing'));

-- Seed baseline lanes
INSERT INTO fulfillment_lane_registry (code, display_name, handler_type, is_active, is_system)
VALUES 
    ('kitchen', 'Pha chế / Bếp', 'kitchen', TRUE, TRUE),
    ('packing', 'Soạn hàng / Đóng gói', 'packing', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- 2. Branch Fulfillment Capabilities (Which branches can fulfill which lanes)
CREATE TABLE IF NOT EXISTS branch_fulfillment_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    lane_code VARCHAR(50) NOT NULL REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_branch_fulfillment_lane UNIQUE (store_id, lane_code)
);

CREATE INDEX IF NOT EXISTS idx_branch_capabilities_store_id
    ON branch_fulfillment_capabilities (store_id);

-- 3. Categories: default_fulfillment_lane
ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS default_fulfillment_lane VARCHAR(50);

ALTER TABLE categories DROP CONSTRAINT IF EXISTS fk_categories_default_fulfillment_lane;
ALTER TABLE categories ADD CONSTRAINT fk_categories_default_fulfillment_lane
    FOREIGN KEY (default_fulfillment_lane)
    REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT;

-- 4. Products: fulfillment_lane becomes nullable explicit override
ALTER TABLE products
    ALTER COLUMN fulfillment_lane DROP DEFAULT;

ALTER TABLE products
    ALTER COLUMN fulfillment_lane DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_products_fulfillment_lane'
    ) THEN
        ALTER TABLE products
            ADD CONSTRAINT fk_products_fulfillment_lane
            FOREIGN KEY (fulfillment_lane)
            REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT;
    END IF;
END $$;

-- 5. Order Items: snapshot fulfillment_lane
ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS fulfillment_lane VARCHAR(50);

ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_fulfillment_lane;
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_fulfillment_lane
    FOREIGN KEY (fulfillment_lane)
    REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT;

-- 6. Fulfillment Tasks & Items hardening
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fulfillment_tasks_lane_check'
    ) THEN
        ALTER TABLE fulfillment_tasks DROP CONSTRAINT fulfillment_tasks_lane_check;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_fulfillment_tasks_lane'
    ) THEN
        ALTER TABLE fulfillment_tasks
            ADD CONSTRAINT fk_fulfillment_tasks_lane
            FOREIGN KEY (lane)
            REFERENCES fulfillment_lane_registry(code) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fulfillment_task_order_item
    ON fulfillment_task_items (order_item_id)
    WHERE order_item_id IS NOT NULL;

CREATE OR REPLACE FUNCTION enforce_fulfillment_task_item_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    task_order_id BIGINT;
    item_order_id BIGINT;
BEGIN
    IF NEW.order_item_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT order_id INTO task_order_id FROM fulfillment_tasks WHERE id = NEW.task_id;
    SELECT order_id INTO item_order_id FROM order_items WHERE id = NEW.order_item_id;
    IF task_order_id IS NULL OR item_order_id IS NULL OR task_order_id <> item_order_id THEN
        RAISE EXCEPTION 'fulfillment task and order item must belong to the same order'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_fulfillment_task_item_order ON fulfillment_task_items;
CREATE TRIGGER trg_fulfillment_task_item_order
BEFORE INSERT OR UPDATE OF task_id, order_item_id ON fulfillment_task_items
FOR EACH ROW EXECUTE FUNCTION enforce_fulfillment_task_item_order();
