-- ==========================================================
-- Migration 0019_category_product_option_presets.sql
-- Persistence for Block 3: Category & Product Option Presets with Lock Protection
-- ==========================================================

-- 1. Option Presets Table (Block 3 Presets for direct subcategories or specific active products)
CREATE TABLE IF NOT EXISTS catalog_option_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    attribute_definition_id BIGINT NOT NULL REFERENCES attribute_definitions(id) ON DELETE CASCADE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_preset_target_type CHECK (target_type IN ('category', 'product')),
    CONSTRAINT uq_catalog_option_preset UNIQUE (target_type, target_id, attribute_definition_id)
);

CREATE INDEX IF NOT EXISTS idx_catalog_option_presets_target
    ON catalog_option_presets (target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_catalog_option_presets_attr_id
    ON catalog_option_presets (attribute_definition_id);

-- 2. Option Preset Values Table (Mapping preset to selected default attribute values)
CREATE TABLE IF NOT EXISTS catalog_option_preset_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id BIGINT NOT NULL REFERENCES catalog_option_presets(id) ON DELETE CASCADE,
    attribute_value_id BIGINT NOT NULL REFERENCES attribute_values(id) ON DELETE CASCADE,
    CONSTRAINT uq_catalog_option_preset_value UNIQUE (preset_id, attribute_value_id)
);

CREATE INDEX IF NOT EXISTS idx_cat_opt_preset_values_preset
    ON catalog_option_preset_values (preset_id);

CREATE INDEX IF NOT EXISTS idx_cat_opt_preset_values_value
    ON catalog_option_preset_values (attribute_value_id);

-- 3. Trigger: Ensure target exists and is valid (Direct subcategory depth=1 for category presets, active product for product presets)
CREATE OR REPLACE FUNCTION enforce_catalog_option_preset_target()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    cat_parent_id BIGINT;
    cat_depth INT;
    cat_exists BOOLEAN := FALSE;
    prod_exists BOOLEAN := FALSE;
BEGIN
    IF NEW.target_type = 'category' THEN
        SELECT parent_id, depth, TRUE INTO cat_parent_id, cat_depth, cat_exists
        FROM categories
        WHERE id = NEW.target_id AND archived_at IS NULL;

        IF NOT cat_exists THEN
            RAISE EXCEPTION 'Category ID % does not exist or is archived', NEW.target_id
                USING ERRCODE = '23503';
        END IF;

        IF cat_parent_id IS NULL OR cat_depth <> 1 THEN
            RAISE EXCEPTION 'Option presets cannot be placed on root categories; only direct subcategories (depth 1) are allowed'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.target_type = 'product' THEN
        SELECT TRUE INTO prod_exists
        FROM products
        WHERE id = NEW.target_id AND status <> 'archived';

        IF NOT prod_exists THEN
            RAISE EXCEPTION 'Product ID % does not exist or is archived', NEW.target_id
                USING ERRCODE = '23503';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_catalog_option_preset_target ON catalog_option_presets;
CREATE TRIGGER trg_catalog_option_preset_target
BEFORE INSERT OR UPDATE OF target_type, target_id ON catalog_option_presets
FOR EACH ROW EXECUTE FUNCTION enforce_catalog_option_preset_target();

-- 4. Trigger: Ensure preset attribute value belongs to the preset's attribute definition
CREATE OR REPLACE FUNCTION enforce_preset_value_attribute_match()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    preset_attr_id BIGINT;
    val_attr_id BIGINT;
BEGIN
    SELECT attribute_definition_id INTO preset_attr_id
    FROM catalog_option_presets
    WHERE id = NEW.preset_id;

    SELECT attribute_definition_id INTO val_attr_id
    FROM attribute_values
    WHERE id = NEW.attribute_value_id;

    IF preset_attr_id IS NULL OR val_attr_id IS NULL OR preset_attr_id <> val_attr_id THEN
        RAISE EXCEPTION 'Attribute value ID % does not belong to attribute definition ID %',
            NEW.attribute_value_id, preset_attr_id
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_preset_value_attribute_match ON catalog_option_preset_values;
CREATE TRIGGER trg_preset_value_attribute_match
BEFORE INSERT OR UPDATE OF attribute_value_id ON catalog_option_preset_values
FOR EACH ROW EXECUTE FUNCTION enforce_preset_value_attribute_match();

-- 5. Preflight View: Report legacy products attached directly to root categories
CREATE OR REPLACE VIEW v_legacy_root_products_preflight AS
SELECT p.id, p.name, p.slug, p.category_id, c.name AS root_name, c.depth
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE c.parent_id IS NULL OR c.depth = 0;
