-- ==========================================================
-- Migration 0020_payment_profiles_and_grouped_checkout.sql
-- Multi-Industry Payment Profiles, Root Category Mapping & Grouped Checkout
-- ==========================================================

-- 1. Table: payment_profiles (Managed strictly by Super Admin)
CREATE TABLE IF NOT EXISTS payment_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100),
    bank_bin VARCHAR(20),
    account_number VARCHAR(50),
    account_holder VARCHAR(100),
    env_prefix VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    version INT NOT NULL DEFAULT 1,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_payment_profile_code_format CHECK (code ~ '^[A-Z0-9_]+$'),
    CONSTRAINT chk_payment_profile_status CHECK (status IN ('pending', 'active', 'disabled'))
);

CREATE INDEX IF NOT EXISTS idx_payment_profiles_status ON payment_profiles(status);
CREATE INDEX IF NOT EXISTS idx_payment_profiles_code ON payment_profiles(code);

-- 2. Table: category_payment_profiles (Mapping Root Category -> Active Payment Profile)
CREATE TABLE IF NOT EXISTS category_payment_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root_category_id BIGINT NOT NULL UNIQUE REFERENCES categories(id) ON DELETE CASCADE,
    payment_profile_id BIGINT NOT NULL REFERENCES payment_profiles(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cat_payment_profiles_cat ON category_payment_profiles(root_category_id);
CREATE INDEX IF NOT EXISTS idx_cat_payment_profiles_profile ON category_payment_profiles(payment_profile_id);

-- Trigger: Ensure category_payment_profiles only maps to ROOT categories (depth = 0 and parent_id IS NULL)
CREATE OR REPLACE FUNCTION enforce_root_category_payment_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    cat_parent_id BIGINT;
    cat_depth INT;
    cat_exists BOOLEAN := FALSE;
BEGIN
    SELECT parent_id, depth, TRUE INTO cat_parent_id, cat_depth, cat_exists
    FROM categories
    WHERE id = NEW.root_category_id AND archived_at IS NULL;

    IF NOT cat_exists THEN
        RAISE EXCEPTION 'Category ID % does not exist or is archived', NEW.root_category_id
            USING ERRCODE = '23503';
    END IF;

    IF cat_parent_id IS NOT NULL OR cat_depth <> 0 THEN
        RAISE EXCEPTION 'Payment profile mapping is only allowed on root categories (depth = 0), category ID % has parent % and depth %',
            NEW.root_category_id, cat_parent_id, cat_depth
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_root_category_payment_profile ON category_payment_profiles;
CREATE TRIGGER trg_enforce_root_category_payment_profile
    BEFORE INSERT OR UPDATE ON category_payment_profiles
    FOR EACH ROW
    EXECUTE FUNCTION enforce_root_category_payment_profile();

-- 3. Table: checkout_groups (Grouped checkout container when cart has multiple root categories)
CREATE TABLE IF NOT EXISTS checkout_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(32) NOT NULL UNIQUE,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    payment_provider VARCHAR(30) NOT NULL DEFAULT 'payos',
    payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
    payment_profile_id BIGINT REFERENCES payment_profiles(id) ON DELETE SET NULL,
    payment_profile_code VARCHAR(50) NOT NULL,
    payment_profile_version INT NOT NULL DEFAULT 1,
    receiver_bank_name VARCHAR(100),
    receiver_account_number VARCHAR(50),
    receiver_account_holder VARCHAR(100),
    payment_link_id VARCHAR(100),
    payos_order_code BIGINT UNIQUE,
    payment_checkout_url TEXT,
    payment_qr_code TEXT,
    payment_created_at TIMESTAMPTZ,
    payment_expires_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    shipping_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    voucher_code VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_checkout_group_payment_status CHECK (payment_status IN ('unpaid', 'paid', 'cancelled', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_checkout_groups_payos_code ON checkout_groups(payos_order_code);
CREATE INDEX IF NOT EXISTS idx_checkout_groups_payment_link ON checkout_groups(payment_link_id);
CREATE INDEX IF NOT EXISTS idx_checkout_groups_store ON checkout_groups(store_id);

-- 4. Table: checkout_group_allocations (Child Order allocation breakdown within a Checkout Group)
CREATE TABLE IF NOT EXISTS checkout_group_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_group_id BIGINT NOT NULL REFERENCES checkout_groups(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    root_category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    root_category_name VARCHAR(100) NOT NULL,
    root_category_slug VARCHAR(100) NOT NULL,
    allocated_subtotal NUMERIC(15, 2) NOT NULL,
    allocated_discount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    allocated_shipping_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    allocated_total NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_checkout_group_alloc_group ON checkout_group_allocations(checkout_group_id);
CREATE INDEX IF NOT EXISTS idx_checkout_group_alloc_order ON checkout_group_allocations(order_id);

-- 5. Extend orders table with checkout group & payment snapshot columns
ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_group_id BIGINT REFERENCES checkout_groups(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS root_category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_profile_id BIGINT REFERENCES payment_profiles(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_profile_code VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_profile_version INT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_bank_name VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_account_number VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_account_holder VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_orders_checkout_group ON orders(checkout_group_id);
CREATE INDEX IF NOT EXISTS idx_orders_root_category ON orders(root_category_id);
CREATE INDEX IF NOT EXISTS idx_orders_payment_profile ON orders(payment_profile_id);

-- 6. Seed initial system default profiles (Safe metadata, no secrets)
INSERT INTO payment_profiles (code, display_name, env_prefix, status, version)
VALUES
    ('LONG_GROUPED_CHECKOUT', 'Long - Grouped Checkout & Hệ Thống Chung', 'PAYOS_PROFILE_LONG_GROUPED_CHECKOUT', 'active', 1),
    ('DEFAULT_LONG', 'Long - Mặc Định Fallback', 'PAYOS_PROFILE_DEFAULT_LONG', 'active', 1)
ON CONFLICT (code) DO NOTHING;
