-- P1 / phase 0026: immutable PayOS payment-attempt history.
--
-- This migration is deliberately additive. Legacy order/group artifacts remain
-- the rollback-compatible mirror until a later enforcement/runtime phase.
-- It neither drops nor replaces any legacy unique index/constraint.

-- Historical artifacts that were audited as unresolvable are retained here as
-- an explicit quarantine record. This is not a payment state and never
-- authorizes profile guessing or creation of a synthetic attempt.
CREATE TABLE IF NOT EXISTS payment_attempt_backfill_quarantine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL CHECK (target_type IN ('order', 'checkout_group')),
    order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT,
    checkout_group_id BIGINT REFERENCES checkout_groups(id) ON DELETE RESTRICT,
    reason_code VARCHAR(80) NOT NULL CHECK (reason_code IN ('HISTORICAL_UNRESOLVABLE')),
    evidence_basis VARCHAR(120) NOT NULL,
    quarantined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((target_type = 'order' AND order_id IS NOT NULL AND checkout_group_id IS NULL)
      OR (target_type = 'checkout_group' AND checkout_group_id IS NOT NULL AND order_id IS NULL)),
    UNIQUE (target_type, order_id, checkout_group_id)
);

CREATE INDEX IF NOT EXISTS idx_payment_attempt_quarantine_target
  ON payment_attempt_backfill_quarantine(target_type, order_id, checkout_group_id);

-- Populate the quarantine before the fail-closed assertions below. The same
-- predicate is repeated in the idempotent insert after the assertions so the
-- precondition and backfill share the exact historical rule.
INSERT INTO payment_attempt_backfill_quarantine (target_type, order_id, reason_code, evidence_basis)
SELECT 'order', o.id, 'HISTORICAL_UNRESOLVABLE', 'expired_unpaid_without_valid_paid_evidence'
FROM orders o
WHERE o.checkout_group_id IS NULL AND o.payment_provider = 'payos' AND o.payos_order_code IS NOT NULL
  AND o.payment_expires_at IS NOT NULL AND o.payment_expires_at <= CURRENT_TIMESTAMP
  AND o.payment_status IN ('unpaid', 'expired') AND o.paid_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM payment_events e WHERE e.provider = 'payos' AND e.order_id = o.id
    AND e.event_type = 'payment.succeeded'
    AND COALESCE(e.payload ->> 'code', e.payload #>> '{data,code}') = '00'
    AND UPPER(COALESCE(e.payload ->> 'status', e.payload #>> '{data,status}', '')) = 'PAID'
    AND NULLIF(BTRIM(COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')), '') ~ '^-?[0-9]+(?:\\.[0-9]+)?$'
    AND COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')::numeric = o.total)
ON CONFLICT (target_type, order_id, checkout_group_id) DO NOTHING;

INSERT INTO payment_attempt_backfill_quarantine (target_type, checkout_group_id, reason_code, evidence_basis)
SELECT 'checkout_group', cg.id, 'HISTORICAL_UNRESOLVABLE', 'expired_unpaid_without_valid_paid_evidence'
FROM checkout_groups cg
WHERE cg.payment_provider = 'payos' AND cg.payos_order_code IS NOT NULL
  AND cg.payment_expires_at IS NOT NULL AND cg.payment_expires_at <= CURRENT_TIMESTAMP
  AND cg.payment_status IN ('unpaid', 'expired') AND cg.paid_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM payment_events e WHERE e.provider = 'payos'
    AND e.event_type = 'payment.succeeded'
    AND (e.payload ->> 'orderCode' = cg.payos_order_code::text OR e.payload #>> '{data,orderCode}' = cg.payos_order_code::text)
    AND COALESCE(e.payload ->> 'code', e.payload #>> '{data,code}') = '00'
    AND UPPER(COALESCE(e.payload ->> 'status', e.payload #>> '{data,status}', '')) = 'PAID'
    AND NULLIF(BTRIM(COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')), '') ~ '^-?[0-9]+(?:\\.[0-9]+)?$'
    AND COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')::numeric = cg.total_amount)
ON CONFLICT (target_type, order_id, checkout_group_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL CHECK (target_type IN ('order', 'checkout_group')),
    order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT,
    checkout_group_id BIGINT REFERENCES checkout_groups(id) ON DELETE RESTRICT,
    provider VARCHAR(50) NOT NULL,
    payment_profile_code VARCHAR(50) NOT NULL,
    payment_profile_version INT,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    provider_order_code BIGINT,
    provider_payment_link_id VARCHAR(100),
    checkout_url TEXT,
    qr_code TEXT,
    status VARCHAR(30) NOT NULL CHECK (status IN ('creating', 'active', 'expired', 'superseded', 'paid', 'failed')),
    failure_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    superseded_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Compatibility pointers are nullable in the additive phase. P1 runtime will
-- write them only after its create/recover workflow is deployed.
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS current_payment_attempt_id BIGINT;
ALTER TABLE checkout_groups
    ADD COLUMN IF NOT EXISTS current_payment_attempt_id BIGINT;

-- Existing event identity remains untouched. These nullable columns let P1
-- attach future (and subsequently backfilled where safe) events to attempts.
ALTER TABLE payment_events
    ADD COLUMN IF NOT EXISTS payment_attempt_id BIGINT,
    ADD COLUMN IF NOT EXISTS checkout_group_id BIGINT,
    ADD COLUMN IF NOT EXISTS payment_profile_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS provider_payment_identity VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_payment_attempts_order_id
    ON payment_attempts(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_attempts_checkout_group_id
    ON payment_attempts(checkout_group_id);
CREATE INDEX IF NOT EXISTS idx_payment_attempts_provider_order_code
    ON payment_attempts(provider, payment_profile_code, provider_order_code)
    WHERE provider_order_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_attempts_provider_link_id
    ON payment_attempts(provider, payment_profile_code, provider_payment_link_id)
    WHERE provider_payment_link_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_attempts_status_expires_at
    ON payment_attempts(status, expires_at)
    WHERE status IN ('creating', 'active', 'expired');
CREATE INDEX IF NOT EXISTS idx_orders_current_payment_attempt
    ON orders(current_payment_attempt_id)
    WHERE current_payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_checkout_groups_current_payment_attempt
    ON checkout_groups(current_payment_attempt_id)
    WHERE current_payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_events_payment_attempt
    ON payment_events(payment_attempt_id)
    WHERE payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_events_provider_profile_identity
    ON payment_events(provider, payment_profile_code, provider_payment_identity)
    WHERE payment_profile_code IS NOT NULL AND provider_payment_identity IS NOT NULL;

-- Backfill is intentionally conservative. A row with any legacy PayOS
-- artifact must be fully interpretable; otherwise this migration aborts before
-- inserting a partial/guessed attempt. No synthetic LEGACY_UNKNOWN profile is
-- ever created.
DO $$
BEGIN
  -- A grouped child is forbidden from having direct PayOS artifacts. Existing
  -- pre-P0 rows may have bypassed the NOT VALID constraint, so fail closed.
  IF EXISTS (
    SELECT 1
    FROM orders o
    WHERE o.checkout_group_id IS NOT NULL
      AND (
        o.payos_order_code IS NOT NULL
        OR o.payment_link_id IS NOT NULL
        OR o.payment_checkout_url IS NOT NULL
        OR o.payment_qr_code IS NOT NULL
        OR o.payment_created_at IS NOT NULL
        OR o.payment_expires_at IS NOT NULL
      )
  ) THEN
    RAISE EXCEPTION '0026 backfill failed: grouped child order has direct PayOS artifacts';
  END IF;

  -- Any legacy artifact outside the known PayOS provider cannot be safely
  -- translated into a PayOS attempt.
  IF EXISTS (
    SELECT 1
    FROM orders o
    WHERE (
        o.payos_order_code IS NOT NULL
        OR o.payment_link_id IS NOT NULL
        OR o.payment_checkout_url IS NOT NULL
        OR o.payment_qr_code IS NOT NULL
        OR o.payment_created_at IS NOT NULL
        OR o.payment_expires_at IS NOT NULL
      )
      AND o.payment_provider IS DISTINCT FROM 'payos'
  ) OR EXISTS (
    SELECT 1
    FROM checkout_groups cg
    WHERE (
        cg.payos_order_code IS NOT NULL
        OR cg.payment_link_id IS NOT NULL
        OR cg.payment_checkout_url IS NOT NULL
        OR cg.payment_qr_code IS NOT NULL
        OR cg.payment_created_at IS NOT NULL
        OR cg.payment_expires_at IS NOT NULL
      )
      AND cg.payment_provider IS DISTINCT FROM 'payos'
  ) THEN
    RAISE EXCEPTION '0026 backfill failed: PayOS artifacts do not declare payment_provider=payos';
  END IF;

  -- Every artifact-bearing target needs an actual profile snapshot that still
  -- resolves to metadata. Disabled historical profiles remain valid snapshots.
  IF EXISTS (
    SELECT 1
    FROM orders o
    WHERE o.checkout_group_id IS NULL
      AND o.payment_provider = 'payos'
      AND (
        o.payos_order_code IS NOT NULL
        OR o.payment_link_id IS NOT NULL
        OR o.payment_checkout_url IS NOT NULL
        OR o.payment_qr_code IS NOT NULL
        OR o.payment_created_at IS NOT NULL
        OR o.payment_expires_at IS NOT NULL
      )
      AND (
        NULLIF(BTRIM(o.payment_profile_code), '') IS NULL
        OR NOT EXISTS (SELECT 1 FROM payment_profiles pp WHERE pp.code = o.payment_profile_code)
      )
      AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'order' AND q.order_id = o.id)
  ) OR EXISTS (
    SELECT 1
    FROM checkout_groups cg
    WHERE (
        cg.payos_order_code IS NOT NULL
        OR cg.payment_link_id IS NOT NULL
        OR cg.payment_checkout_url IS NOT NULL
        OR cg.payment_qr_code IS NOT NULL
        OR cg.payment_created_at IS NOT NULL
        OR cg.payment_expires_at IS NOT NULL
      )
      AND (
        NULLIF(BTRIM(cg.payment_profile_code), '') IS NULL
        OR NOT EXISTS (SELECT 1 FROM payment_profiles pp WHERE pp.code = cg.payment_profile_code)
      )
      AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'checkout_group' AND q.checkout_group_id = cg.id)
  ) THEN
    RAISE EXCEPTION '0026 backfill failed: legacy PayOS artifact has no resolvable payment profile snapshot';
  END IF;

  -- A backfilled attempt needs a stable provider order code and timestamps.
  -- "creating" is only the reserved-code/no-link state; other partial link
  -- shapes are ambiguous and must be repaired before applying 0026.
  IF EXISTS (
    SELECT 1
    FROM orders o
    WHERE o.checkout_group_id IS NULL
      AND o.payment_provider = 'payos'
      AND (
        o.payos_order_code IS NOT NULL
        OR o.payment_link_id IS NOT NULL
        OR o.payment_checkout_url IS NOT NULL
        OR o.payment_qr_code IS NOT NULL
        OR o.payment_created_at IS NOT NULL
        OR o.payment_expires_at IS NOT NULL
      )
      AND (
        o.payos_order_code IS NULL
        OR o.payment_created_at IS NULL
        OR o.payment_expires_at IS NULL
        OR (o.payment_link_id IS NULL AND (o.payment_checkout_url IS NOT NULL OR o.payment_qr_code IS NOT NULL))
        OR (o.payment_link_id IS NOT NULL AND o.payment_checkout_url IS NULL AND o.payment_qr_code IS NULL)
        OR (o.payment_status IN ('paid', 'expired') AND o.payment_link_id IS NULL)
        OR (o.payment_status = 'paid' AND o.paid_at IS NULL)
      )
      AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'order' AND q.order_id = o.id)
  ) OR EXISTS (
    SELECT 1
    FROM checkout_groups cg
    WHERE (
        cg.payos_order_code IS NOT NULL
        OR cg.payment_link_id IS NOT NULL
        OR cg.payment_checkout_url IS NOT NULL
        OR cg.payment_qr_code IS NOT NULL
        OR cg.payment_created_at IS NOT NULL
        OR cg.payment_expires_at IS NOT NULL
      )
      AND (
        cg.payment_status NOT IN ('unpaid', 'paid', 'expired')
        OR cg.payos_order_code IS NULL
        OR cg.payment_created_at IS NULL
        OR cg.payment_expires_at IS NULL
        OR (cg.payment_link_id IS NULL AND (cg.payment_checkout_url IS NOT NULL OR cg.payment_qr_code IS NOT NULL))
        OR (cg.payment_link_id IS NOT NULL AND cg.payment_checkout_url IS NULL AND cg.payment_qr_code IS NULL)
        OR (cg.payment_status IN ('paid', 'expired') AND cg.payment_link_id IS NULL)
        OR (cg.payment_status = 'paid' AND cg.paid_at IS NULL)
      )
      AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'checkout_group' AND q.checkout_group_id = cg.id)
  ) THEN
    RAISE EXCEPTION '0026 backfill failed: legacy PayOS artifact shape or status is not safely interpretable';
  END IF;

  -- P1 will resolve an incoming raw identifier against profile snapshots. It
  -- cannot safely start from same-profile collisions in legacy artifacts.
  IF EXISTS (
    WITH legacy_attempts AS (
      SELECT 'payos'::VARCHAR AS provider, o.payment_profile_code, o.payos_order_code, o.payment_link_id
      FROM orders o
      WHERE o.checkout_group_id IS NULL AND o.payment_provider = 'payos' AND o.payos_order_code IS NOT NULL
      UNION ALL
      SELECT cg.payment_provider, cg.payment_profile_code, cg.payos_order_code, cg.payment_link_id
      FROM checkout_groups cg
      WHERE cg.payment_provider = 'payos' AND cg.payos_order_code IS NOT NULL
    )
    SELECT 1
    FROM legacy_attempts
    GROUP BY provider, payment_profile_code, payos_order_code
    HAVING COUNT(*) > 1
  ) OR EXISTS (
    WITH legacy_attempts AS (
      SELECT 'payos'::VARCHAR AS provider, o.payment_profile_code, o.payos_order_code, o.payment_link_id
      FROM orders o
      WHERE o.checkout_group_id IS NULL AND o.payment_provider = 'payos' AND o.payment_link_id IS NOT NULL
      UNION ALL
      SELECT cg.payment_provider, cg.payment_profile_code, cg.payos_order_code, cg.payment_link_id
      FROM checkout_groups cg
      WHERE cg.payment_provider = 'payos' AND cg.payment_link_id IS NOT NULL
    )
    SELECT 1
    FROM legacy_attempts
    GROUP BY provider, payment_profile_code, payment_link_id
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION '0026 backfill failed: same-profile legacy provider identity collision';
  END IF;
END $$;

-- Record only the already-audited, unresolvable legacy shapes. The predicate
-- is deliberately conservative: expired + unpaid/expired + no paid timestamp
-- + no valid paid evidence. Any other blocker remains a hard failure above.
INSERT INTO payment_attempt_backfill_quarantine (target_type, order_id, reason_code, evidence_basis)
SELECT 'order', o.id, 'HISTORICAL_UNRESOLVABLE', 'expired_unpaid_without_valid_paid_evidence'
FROM orders o
WHERE o.checkout_group_id IS NULL AND o.payment_provider = 'payos'
  AND o.payos_order_code IS NOT NULL
  AND o.payment_expires_at IS NOT NULL AND o.payment_expires_at <= CURRENT_TIMESTAMP
  AND o.payment_status IN ('unpaid', 'expired') AND o.paid_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM payment_events e
    WHERE e.provider = 'payos' AND e.order_id = o.id
      AND e.event_type = 'payment.succeeded'
      AND COALESCE(e.payload ->> 'code', e.payload #>> '{data,code}') = '00'
      AND UPPER(COALESCE(e.payload ->> 'status', e.payload #>> '{data,status}', '')) = 'PAID'
      AND NULLIF(BTRIM(COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')), '') ~ '^-?[0-9]+(?:\\.[0-9]+)?$'
      AND (COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')::numeric = o.total)
  )
ON CONFLICT (target_type, order_id, checkout_group_id) DO NOTHING;

INSERT INTO payment_attempt_backfill_quarantine (target_type, checkout_group_id, reason_code, evidence_basis)
SELECT 'checkout_group', cg.id, 'HISTORICAL_UNRESOLVABLE', 'expired_unpaid_without_valid_paid_evidence'
FROM checkout_groups cg
WHERE cg.payment_provider = 'payos'
  AND cg.payos_order_code IS NOT NULL
  AND cg.payment_expires_at IS NOT NULL AND cg.payment_expires_at <= CURRENT_TIMESTAMP
  AND cg.payment_status IN ('unpaid', 'expired') AND cg.paid_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM payment_events e
    WHERE e.provider = 'payos'
      AND e.event_type = 'payment.succeeded'
      AND (e.payload ->> 'orderCode' = cg.payos_order_code::text OR e.payload #>> '{data,orderCode}' = cg.payos_order_code::text)
      AND COALESCE(e.payload ->> 'code', e.payload #>> '{data,code}') = '00'
      AND UPPER(COALESCE(e.payload ->> 'status', e.payload #>> '{data,status}', '')) = 'PAID'
      AND NULLIF(BTRIM(COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')), '') ~ '^-?[0-9]+(?:\\.[0-9]+)?$'
      AND (COALESCE(e.payload ->> 'amount', e.payload #>> '{data,amount}')::numeric = cg.total_amount)
  )
ON CONFLICT (target_type, order_id, checkout_group_id) DO NOTHING;

-- The migration runner holds the advisory lock. NOT EXISTS makes this safe for
-- a manual rehearsal re-run without relying on a new unique constraint.
INSERT INTO payment_attempts (
  target_type, order_id, provider, payment_profile_code, payment_profile_version,
  amount, provider_order_code, provider_payment_link_id, checkout_url, qr_code,
  status, created_at, activated_at, expires_at, expired_at, paid_at, updated_at
)
SELECT
  'order', o.id, 'payos', o.payment_profile_code, o.payment_profile_version,
  o.total, o.payos_order_code, o.payment_link_id, o.payment_checkout_url, o.payment_qr_code,
  CASE
    WHEN o.payment_status = 'paid' THEN 'paid'
    WHEN o.payment_status = 'expired' THEN 'expired'
    WHEN o.payment_link_id IS NULL THEN 'creating'
    ELSE 'active'
  END,
  o.payment_created_at,
  CASE WHEN o.payment_link_id IS NOT NULL THEN o.payment_created_at END,
  o.payment_expires_at,
  CASE WHEN o.payment_status = 'expired' THEN o.payment_expires_at END,
  CASE WHEN o.payment_status = 'paid' THEN o.paid_at END,
  COALESCE(o.paid_at, o.payment_expires_at, o.payment_created_at)
FROM orders o
WHERE o.checkout_group_id IS NULL
  AND o.payment_provider = 'payos'
  AND o.payos_order_code IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'order' AND q.order_id = o.id)
  AND NOT EXISTS (SELECT 1 FROM payment_attempts pa WHERE pa.order_id = o.id);

INSERT INTO payment_attempts (
  target_type, checkout_group_id, provider, payment_profile_code, payment_profile_version,
  amount, provider_order_code, provider_payment_link_id, checkout_url, qr_code,
  status, created_at, activated_at, expires_at, expired_at, paid_at, updated_at
)
SELECT
  'checkout_group', cg.id, 'payos', cg.payment_profile_code, cg.payment_profile_version,
  cg.total_amount, cg.payos_order_code, cg.payment_link_id, cg.payment_checkout_url, cg.payment_qr_code,
  CASE
    WHEN cg.payment_status = 'paid' THEN 'paid'
    WHEN cg.payment_status = 'expired' THEN 'expired'
    WHEN cg.payment_link_id IS NULL THEN 'creating'
    ELSE 'active'
  END,
  cg.payment_created_at,
  CASE WHEN cg.payment_link_id IS NOT NULL THEN cg.payment_created_at END,
  cg.payment_expires_at,
  CASE WHEN cg.payment_status = 'expired' THEN cg.payment_expires_at END,
  CASE WHEN cg.payment_status = 'paid' THEN cg.paid_at END,
  COALESCE(cg.paid_at, cg.payment_expires_at, cg.payment_created_at)
FROM checkout_groups cg
WHERE cg.payment_provider = 'payos'
  AND cg.payos_order_code IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM payment_attempt_backfill_quarantine q WHERE q.target_type = 'checkout_group' AND q.checkout_group_id = cg.id)
  AND NOT EXISTS (SELECT 1 FROM payment_attempts pa WHERE pa.checkout_group_id = cg.id);

UPDATE orders o
SET current_payment_attempt_id = pa.id
FROM payment_attempts pa
WHERE pa.order_id = o.id
  AND o.current_payment_attempt_id IS NULL;

UPDATE checkout_groups cg
SET current_payment_attempt_id = pa.id
FROM payment_attempts pa
WHERE pa.checkout_group_id = cg.id
  AND cg.current_payment_attempt_id IS NULL;
