-- P1 / phase 0026: immutable PayOS payment-attempt history.
-- The executor supplies and verifies the audited legacy manifest in a
-- transaction-local TEMP table. This migration deliberately does not classify
-- legacy rows itself.

DO $$
BEGIN
  IF to_regclass('pg_temp.p1_legacy_quarantine_manifest_input') IS NULL THEN
    RAISE EXCEPTION '0026 requires executor-provided audited manifest input';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS legacy_payment_quarantine_manifest (
    target_kind VARCHAR(30) NOT NULL CHECK (target_kind IN ('direct_order', 'checkout_group')),
    target_id BIGINT NOT NULL,
    classification VARCHAR(50) NOT NULL CHECK (classification IN ('ACTIVE_PAYMENT_REQUIRES_REPAIR', 'SAFE_TO_SKIP_HISTORY', 'AMBIGUOUS_BLOCK')),
    classifier_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (target_kind, target_id)
);

INSERT INTO legacy_payment_quarantine_manifest (target_kind, target_id, classification, classifier_version)
SELECT target_kind, target_id, classification, classifier_version
FROM p1_legacy_quarantine_manifest_input
ON CONFLICT (target_kind, target_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL CHECK (target_type IN ('order', 'checkout_group')),
    order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT,
    checkout_group_id BIGINT REFERENCES checkout_groups(id) ON DELETE RESTRICT,
    provider VARCHAR(50) NOT NULL,
    payment_profile_code VARCHAR(50) NOT NULL,
    payment_profile_version INT,
    amount NUMERIC(15, 2) NOT NULL CHECK (amount >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    provider_order_code BIGINT,
    provider_payment_link_id VARCHAR(100),
    checkout_url TEXT,
    qr_code TEXT,
    status VARCHAR(30) NOT NULL CHECK (status IN ('creating', 'active', 'expired', 'superseded', 'paid', 'failed')),
    failure_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    superseded_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS current_payment_attempt_id BIGINT;
ALTER TABLE checkout_groups ADD COLUMN IF NOT EXISTS current_payment_attempt_id BIGINT;
ALTER TABLE payment_events
    ADD COLUMN IF NOT EXISTS payment_attempt_id BIGINT,
    ADD COLUMN IF NOT EXISTS checkout_group_id BIGINT,
    ADD COLUMN IF NOT EXISTS payment_profile_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS provider_payment_identity VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_payment_attempts_order_id ON payment_attempts(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_attempts_checkout_group_id ON payment_attempts(checkout_group_id);
CREATE INDEX IF NOT EXISTS idx_payment_attempts_provider_order_code
  ON payment_attempts(provider, payment_profile_code, provider_order_code)
  WHERE provider_order_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_attempts_provider_link_id
  ON payment_attempts(provider, payment_profile_code, provider_payment_link_id)
  WHERE provider_payment_link_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_attempts_status_expires_at
  ON payment_attempts(status, expires_at)
  WHERE status IN ('creating', 'active', 'expired');
CREATE INDEX IF NOT EXISTS idx_orders_current_payment_attempt
  ON orders(current_payment_attempt_id) WHERE current_payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_checkout_groups_current_payment_attempt
  ON checkout_groups(current_payment_attempt_id) WHERE current_payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_events_payment_attempt
  ON payment_events(payment_attempt_id) WHERE payment_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_events_provider_profile_identity
  ON payment_events(provider, payment_profile_code, provider_payment_identity)
  WHERE payment_profile_code IS NOT NULL AND provider_payment_identity IS NOT NULL;

-- Only targets present in the executor-verified manifest are skipped. The
-- application-layer classifier has already fail-closed before this SQL runs.
INSERT INTO payment_attempts (
  target_type, order_id, provider, payment_profile_code, payment_profile_version,
  amount, provider_order_code, provider_payment_link_id, checkout_url, qr_code,
  status, created_at, activated_at, expires_at, expired_at, paid_at, updated_at
)
SELECT
  'order', o.id, 'payos', o.payment_profile_code, o.payment_profile_version,
  o.total, o.payos_order_code, o.payment_link_id, o.payment_checkout_url, o.payment_qr_code,
  CASE WHEN o.payment_status = 'paid' THEN 'paid'
       WHEN o.payment_status = 'expired' THEN 'expired'
       WHEN o.payment_link_id IS NULL THEN 'creating' ELSE 'active' END,
  o.payment_created_at,
  CASE WHEN o.payment_link_id IS NOT NULL THEN o.payment_created_at END,
  o.payment_expires_at,
  CASE WHEN o.payment_status = 'expired' THEN o.payment_expires_at END,
  CASE WHEN o.payment_status = 'paid' THEN o.paid_at END,
  COALESCE(o.paid_at, o.payment_expires_at, o.payment_created_at)
FROM orders o
WHERE o.checkout_group_id IS NULL AND o.payment_provider = 'payos'
  AND o.payos_order_code IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM legacy_payment_quarantine_manifest q WHERE q.target_kind = 'direct_order' AND q.target_id = o.id)
  AND NOT EXISTS (SELECT 1 FROM payment_attempts pa WHERE pa.order_id = o.id);

INSERT INTO payment_attempts (
  target_type, checkout_group_id, provider, payment_profile_code, payment_profile_version,
  amount, provider_order_code, provider_payment_link_id, checkout_url, qr_code,
  status, created_at, activated_at, expires_at, expired_at, paid_at, updated_at
)
SELECT
  'checkout_group', cg.id, 'payos', cg.payment_profile_code, cg.payment_profile_version,
  cg.total_amount, cg.payos_order_code, cg.payment_link_id, cg.payment_checkout_url, cg.payment_qr_code,
  CASE WHEN cg.payment_status = 'paid' THEN 'paid'
       WHEN cg.payment_status = 'expired' THEN 'expired'
       WHEN cg.payment_link_id IS NULL THEN 'creating' ELSE 'active' END,
  cg.payment_created_at,
  CASE WHEN cg.payment_link_id IS NOT NULL THEN cg.payment_created_at END,
  cg.payment_expires_at,
  CASE WHEN cg.payment_status = 'expired' THEN cg.payment_expires_at END,
  CASE WHEN cg.payment_status = 'paid' THEN cg.paid_at END,
  COALESCE(cg.paid_at, cg.payment_expires_at, cg.payment_created_at)
FROM checkout_groups cg
WHERE cg.payment_provider = 'payos' AND cg.payos_order_code IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM legacy_payment_quarantine_manifest q WHERE q.target_kind = 'checkout_group' AND q.target_id = cg.id)
  AND NOT EXISTS (SELECT 1 FROM payment_attempts pa WHERE pa.checkout_group_id = cg.id);

UPDATE orders o SET current_payment_attempt_id = pa.id
FROM payment_attempts pa
WHERE pa.order_id = o.id AND o.current_payment_attempt_id IS NULL;

UPDATE checkout_groups cg SET current_payment_attempt_id = pa.id
FROM payment_attempts pa
WHERE pa.checkout_group_id = cg.id AND cg.current_payment_attempt_id IS NULL;
