-- 0028_product_reviews.sql
-- Additive migration: immutable review revisions, media, replies, upload intents.
-- Preserves legacy reviews table; adds purchase verification and revision chain.
-- Do NOT apply before 0027_payment_attempts_additive.sql is release-ready.

-- =============================================================
-- 1. reviews — add purchase verification & revision columns
-- =============================================================
ALTER TABLE reviews
    ADD COLUMN IF NOT EXISTS purchase_verified_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS current_revision_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS visibility_status VARCHAR(20) NOT NULL DEFAULT 'visible'
        CHECK (visibility_status IN ('visible', 'hidden')),
    ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS hidden_by BIGINT NULL REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS hidden_reason VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS edit_window_expires_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS customer_edit_used_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- =============================================================
-- 2. review_revisions — immutable customer-authored content
-- =============================================================
CREATE TABLE IF NOT EXISTS review_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    sequence SMALLINT NOT NULL CHECK (sequence >= 1),
    revision_type VARCHAR(20) NOT NULL CHECK (revision_type IN ('original', 'customer_edit')),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (review_id, sequence)
);

-- At most one customer_edit per review
CREATE UNIQUE INDEX IF NOT EXISTS uq_review_revisions_one_edit
    ON review_revisions(review_id) WHERE revision_type = 'customer_edit';

-- =============================================================
-- 3. review_replies — one admin reply per review
-- =============================================================
CREATE TABLE IF NOT EXISTS review_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL UNIQUE REFERENCES reviews(id) ON DELETE CASCADE,
    admin_user_id BIGINT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================
-- 4. review_media — immutable media attachments per revision
-- =============================================================
CREATE TABLE IF NOT EXISTS review_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_revision_id BIGINT NOT NULL REFERENCES review_revisions(id) ON DELETE CASCADE,
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('image', 'video')),
    storage_key VARCHAR(500) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    byte_size INTEGER NOT NULL CHECK (byte_size > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- At most one image and one video per revision
CREATE UNIQUE INDEX IF NOT EXISTS uq_review_media_one_image
    ON review_media(review_revision_id) WHERE media_type = 'image';
CREATE UNIQUE INDEX IF NOT EXISTS uq_review_media_one_video
    ON review_media(review_revision_id) WHERE media_type = 'video';

-- =============================================================
-- 5. review_media_uploads — pre-auth upload intents
-- =============================================================
CREATE TABLE IF NOT EXISTS review_media_uploads (
    id UUID PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    action VARCHAR(20) NOT NULL CHECK (action IN ('create_original', 'edit_revision')),
    review_id BIGINT NULL REFERENCES reviews(id),
    order_id BIGINT NULL REFERENCES orders(id),
    order_item_id BIGINT NULL REFERENCES order_items(id),
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('image', 'video')),
    requested_content_type VARCHAR(100) NOT NULL,
    requested_byte_size INTEGER NOT NULL CHECK (requested_byte_size > 0),
    storage_key VARCHAR(500) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ NULL,
    attached_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review_upload_intent UNIQUE (id)
);

CREATE INDEX IF NOT EXISTS idx_review_media_uploads_owner
    ON review_media_uploads(owner_user_id, expires_at)
    WHERE claimed_at IS NULL;

-- =============================================================
-- 6. Partial unique index on verified order_item_id
-- =============================================================
-- Only one verified review per order_item. Created after backfill to avoid
-- collision failures — run the verification script first.
CREATE UNIQUE INDEX IF NOT EXISTS uq_reviews_verified_order_item
    ON reviews(order_item_id) WHERE purchase_verified_at IS NOT NULL;

-- =============================================================
-- 7. Indexes for public reads and admin moderation
-- =============================================================
CREATE INDEX IF NOT EXISTS idx_reviews_public_list
    ON reviews(product_id, visibility_status, created_at DESC)
    WHERE purchase_verified_at IS NOT NULL AND visibility_status = 'visible';

CREATE INDEX IF NOT EXISTS idx_reviews_admin_list
    ON reviews(visibility_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_revisions_current
    ON reviews(current_revision_id)
    WHERE current_revision_id IS NOT NULL;

-- =============================================================
-- 8. Backfill original revisions for legacy reviews
-- =============================================================
DO $$
DECLARE
    r RECORD;
    v_revision_id BIGINT;
    v_verified_at TIMESTAMPTZ;
    v_order_status VARCHAR(30);
BEGIN
    FOR r IN
        SELECT
            rev.id AS review_id,
            rev.user_id,
            rev.product_id,
            rev.order_item_id,
            rev.rating,
            rev.comment,
            rev.created_at,
            oi.order_id,
            o.user_id AS order_user_id
        FROM reviews rev
        LEFT JOIN order_items oi ON oi.id = rev.order_item_id
        LEFT JOIN orders o ON o.id = oi.order_id
        WHERE rev.current_revision_id IS NULL
        ORDER BY rev.id
    LOOP
        -- Determine if this is a verified purchase
        v_verified_at := NULL;
        IF r.order_id IS NOT NULL AND r.order_user_id = r.user_id THEN
            SELECT status INTO v_order_status
            FROM order_status_history
            WHERE order_id = r.order_id
            ORDER BY id DESC
            LIMIT 1;

            IF v_order_status = 'Hoàn thành' THEN
                v_verified_at := COALESCE(r.created_at, NOW());
            END IF;
        END IF;

        -- Create original revision
        INSERT INTO review_revisions (review_id, sequence, revision_type, rating, comment, created_at)
        VALUES (r.review_id, 1, 'original', r.rating, r.comment, r.created_at)
        RETURNING id INTO v_revision_id;

        -- Update review with revision pointer and verification
        UPDATE reviews
        SET
            current_revision_id = v_revision_id,
            purchase_verified_at = v_verified_at,
            updated_at = NOW()
        WHERE id = r.review_id;

        -- If legacy row is verified and has image_urls, migrate media
        IF v_verified_at IS NOT NULL AND r.comment IS NOT NULL THEN
            -- Legacy image_urls are stored as comma-separated or JSON array in TEXT.
            -- We preserve them; no automated migration to review_media because
            -- legacy storage (Data URL / URL) has no reliable storage_key.
            -- This is a known data debt noted in the design spec.
            NULL;
        END IF;
    END LOOP;
END $$;

-- =============================================================
-- 9. Update products.rating and products.review_count from backfill
-- =============================================================
UPDATE products p
SET
    rating = COALESCE((
        SELECT ROUND(AVG(rr.rating)::numeric, 1)
        FROM reviews rev
        JOIN review_revisions rr ON rr.id = rev.current_revision_id
        WHERE rev.product_id = p.id
          AND rev.purchase_verified_at IS NOT NULL
          AND rev.visibility_status = 'visible'
    ), 0),
    review_count = (
        SELECT COUNT(*)
        FROM reviews rev
        WHERE rev.product_id = p.id
          AND rev.purchase_verified_at IS NOT NULL
          AND rev.visibility_status = 'visible'
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_reviews_current_revision'
          AND conrelid = 'reviews'::regclass
    ) THEN
        ALTER TABLE reviews
            ADD CONSTRAINT fk_reviews_current_revision
            FOREIGN KEY (current_revision_id) REFERENCES review_revisions(id);
    END IF;
END $$;
