-- ==========================================================
-- Migration 0029_auth_email_staff_accounts.sql
-- Persistent Email OTP Challenges, Email Verification & Staff
-- Account Lifecycle Support
--
-- WARNING: Additive only. Do not alter payment/review tables
-- or rewrite existing users. Do not apply to production.
-- ==========================================================

-- 1. Add email_verified_at to users (nullable, server-owned)
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ DEFAULT NULL;

COMMENT ON COLUMN users.email_verified_at IS
    'Server-owned proof that the current email was verified by the user. Cleared on email change.';

-- 2. Auth Email Challenges table
CREATE TABLE IF NOT EXISTS auth_email_challenges (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    email       VARCHAR(320) NOT NULL,
    purpose     VARCHAR(50) NOT NULL CHECK (purpose IN ('PASSWORD_RESET', 'EMAIL_VERIFICATION', 'STAFF_INVITE')),
    secret_hash CHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INTEGER NOT NULL CHECK (max_attempts > 0),
    sent_at     TIMESTAMPTZ DEFAULT NULL,
    consumed_at TIMESTAMPTZ DEFAULT NULL,
    revoked_at  TIMESTAMPTZ DEFAULT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata    JSONB DEFAULT NULL
);

COMMENT ON TABLE auth_email_challenges IS
    'Persistent HMAC-protected email challenges for password reset, email verification, and staff invitation.';

COMMENT ON COLUMN auth_email_challenges.secret_hash IS
    'HMAC-SHA256 of the secret (OTP code or invitation token). Never plaintext.';
COMMENT ON COLUMN auth_email_challenges.metadata IS
    'Optional JSONB context (e.g. invitation target role/branch). Never store secrets/tokens.';

-- Indexes for auth_email_challenges
CREATE INDEX IF NOT EXISTS idx_aec_user_purpose
    ON auth_email_challenges (user_id, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_aec_email_purpose
    ON auth_email_challenges (email, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_aec_expiry
    ON auth_email_challenges (expires_at)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

COMMENT ON INDEX idx_aec_user_purpose IS 'Lookup active challenges by user and purpose';
COMMENT ON INDEX idx_aec_email_purpose IS 'Lookup active challenges by email and purpose';
COMMENT ON INDEX idx_aec_expiry IS 'Fast expiry cleanup for un-consumed, un-revoked challenges';