-- 0030_preorder_v1.sql
-- Additive preorder aggregate. It deliberately does not alter payment-attempt,
-- review, or auth history. All timestamps are TIMESTAMPTZ.

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE promotions
  ADD COLUMN IF NOT EXISTS applies_to_preorder BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS preorder_store_settings (
  store_id BIGINT PRIMARY KEY REFERENCES stores(id) ON DELETE RESTRICT,
  is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  responsible_manager_id BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preorders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_code VARCHAR(64) NOT NULL UNIQUE,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  customer_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  checkout_idempotency_key VARCHAR(255) NOT NULL,
  checkout_group_id BIGINT NULL UNIQUE REFERENCES checkout_groups(id) ON DELETE RESTRICT,
  scheduled_start_at TIMESTAMPTZ NOT NULL,
  scheduled_end_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(40) NOT NULL CHECK (status IN (
    'AWAITING_PAYMENT', 'PENDING_MANAGER_CONFIRMATION', 'CONFIRMED',
    'CHECKED_IN', 'COMPLETED', 'CUSTOMER_CANCELLED', 'NO_SHOW',
    'PAYMENT_EXPIRED', 'LATE_PAID_REQUIRES_ACTION'
  )),
  responsible_manager_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  confirmed_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  confirmed_at TIMESTAMPTZ NULL,
  checked_in_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  checked_in_at TIMESTAMPTZ NULL,
  late_minutes INTEGER NULL CHECK (late_minutes IS NULL OR late_minutes >= 0),
  completed_at TIMESTAMPTZ NULL,
  cancelled_at TIMESTAMPTZ NULL,
  cancel_reason VARCHAR(500) NULL,
  payment_expired_at TIMESTAMPTZ NULL,
  late_paid_at TIMESTAMPTZ NULL,
  reschedule_count SMALLINT NOT NULL DEFAULT 0 CHECK (reschedule_count BETWEEN 0 AND 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_preorders_slot_one_hour CHECK (scheduled_end_at = scheduled_start_at + INTERVAL '1 hour')
);

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS preorder_id BIGINT NULL REFERENCES preorders(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_orders_preorder_id ON orders(preorder_id) WHERE preorder_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_preorders_direct_order
  ON orders(preorder_id) WHERE preorder_id IS NOT NULL AND checkout_group_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_preorders_store_schedule
  ON preorders(store_id, scheduled_start_at, status);
CREATE INDEX IF NOT EXISTS idx_preorders_customer_created
  ON preorders(customer_user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_preorders_customer_checkout_idempotency
  ON preorders(customer_user_id, checkout_idempotency_key);
CREATE INDEX IF NOT EXISTS idx_preorders_pending_due
  ON preorders(status, scheduled_start_at)
  WHERE status IN ('PENDING_MANAGER_CONFIRMATION', 'CONFIRMED');

CREATE TABLE IF NOT EXISTS preorder_table_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL UNIQUE REFERENCES preorders(id) ON DELETE RESTRICT,
  table_id BIGINT NOT NULL REFERENCES tables(id) ON DELETE RESTRICT,
  reserved_from TIMESTAMPTZ NOT NULL,
  reserved_until TIMESTAMPTZ NOT NULL,
  status VARCHAR(24) NOT NULL CHECK (status IN ('pending_payment', 'held', 'checked_in', 'released', 'cancelled', 'expired')),
  released_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_preorder_table_reservation_interval CHECK (reserved_until = reserved_from + INTERVAL '90 minutes')
);

CREATE INDEX IF NOT EXISTS idx_preorder_table_reservations_active
  ON preorder_table_reservations(table_id, reserved_from, reserved_until)
  WHERE status IN ('pending_payment', 'held', 'checked_in');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ex_preorder_table_reservations_active'
      AND conrelid = 'preorder_table_reservations'::regclass
  ) THEN
    ALTER TABLE preorder_table_reservations
      ADD CONSTRAINT ex_preorder_table_reservations_active
      EXCLUDE USING gist (
        table_id WITH =,
        tstzrange(reserved_from, reserved_until, '[)') WITH &&
      ) WHERE (status IN ('pending_payment', 'held', 'checked_in'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS preorder_reschedule_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL UNIQUE REFERENCES preorders(id) ON DELETE RESTRICT,
  old_scheduled_start_at TIMESTAMPTZ NOT NULL,
  old_scheduled_end_at TIMESTAMPTZ NOT NULL,
  new_scheduled_start_at TIMESTAMPTZ NOT NULL,
  new_scheduled_end_at TIMESTAMPTZ NOT NULL,
  manager_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reason VARCHAR(500) NOT NULL,
  customer_agreement_recorded_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_preorder_reschedule_old_slot CHECK (old_scheduled_end_at = old_scheduled_start_at + INTERVAL '1 hour'),
  CONSTRAINT chk_preorder_reschedule_new_slot CHECK (new_scheduled_end_at = new_scheduled_start_at + INTERVAL '1 hour')
);

CREATE TABLE IF NOT EXISTS preorder_confirmation_incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL UNIQUE REFERENCES preorders(id) ON DELETE RESTRICT,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  responsible_manager_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  scheduled_start_at TIMESTAMPTZ NOT NULL,
  reminder_t60_sent_at TIMESTAMPTZ NULL,
  urgent_t30_sent_at TIMESTAMPTZ NULL,
  breached_at TIMESTAMPTZ NULL,
  confirmed_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  resolved_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  resolved_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_preorder_confirmation_incidents_due
  ON preorder_confirmation_incidents(scheduled_start_at)
  WHERE breached_at IS NULL AND resolved_at IS NULL;

CREATE TABLE IF NOT EXISTS manager_preorder_strikes (
  manager_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
  confirmed_breach_count INTEGER NOT NULL DEFAULT 0 CHECK (confirmed_breach_count >= 0),
  last_confirmed_breach_at TIMESTAMPTZ NULL,
  disabled_by_preorder_at TIMESTAMPTZ NULL,
  reset_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reset_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preorder_notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL REFERENCES preorders(id) ON DELETE RESTRICT,
  event_type VARCHAR(60) NOT NULL,
  recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  channel VARCHAR(20) NOT NULL CHECK (channel IN ('in_app', 'email')),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  processing_at TIMESTAMPTZ NULL,
  sent_at TIMESTAMPTZ NULL,
  last_error_code VARCHAR(80) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_preorder_notification_delivery UNIQUE (preorder_id, event_type, recipient_user_id, channel)
);
CREATE INDEX IF NOT EXISTS idx_preorder_notification_deliveries_pending
  ON preorder_notification_deliveries(status, created_at)
  WHERE status IN ('pending', 'processing', 'failed');

CREATE OR REPLACE FUNCTION validate_preorder_store_settings_manager()
RETURNS trigger AS $$
DECLARE
  v_role VARCHAR(40);
  v_branch BIGINT;
BEGIN
  IF NEW.responsible_manager_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT admin_role, admin_branch_id INTO v_role, v_branch
  FROM users WHERE id = NEW.responsible_manager_id AND is_active = TRUE;
  IF v_role IS DISTINCT FROM 'manager' OR v_branch IS DISTINCT FROM NEW.store_id THEN
    RAISE EXCEPTION 'preorder responsible manager must be active manager of the same store';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_preorder_store_settings_manager ON preorder_store_settings;
CREATE TRIGGER trg_preorder_store_settings_manager
BEFORE INSERT OR UPDATE OF responsible_manager_id, store_id ON preorder_store_settings
FOR EACH ROW EXECUTE FUNCTION validate_preorder_store_settings_manager();

CREATE OR REPLACE FUNCTION validate_order_preorder_link()
RETURNS trigger AS $$
DECLARE
  v_store BIGINT;
  v_group BIGINT;
BEGIN
  IF NEW.preorder_id IS NULL THEN RETURN NEW; END IF;
  SELECT store_id, checkout_group_id INTO v_store, v_group FROM preorders WHERE id = NEW.preorder_id;
  IF NOT FOUND OR v_store IS DISTINCT FROM NEW.store_id THEN
    RAISE EXCEPTION 'preorder order link must use the preorder store';
  END IF;
  IF v_group IS NOT NULL AND NEW.checkout_group_id IS DISTINCT FROM v_group THEN
    RAISE EXCEPTION 'preorder grouped child must belong to preorder checkout group';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_validate_preorder_link ON orders;
CREATE TRIGGER trg_orders_validate_preorder_link
BEFORE INSERT OR UPDATE OF preorder_id, store_id, checkout_group_id ON orders
FOR EACH ROW EXECUTE FUNCTION validate_order_preorder_link();

-- Grouped children are inserted before the preorder aggregate receives the
-- checkout-group pointer. Validate that later pointer swap too, otherwise a
-- malformed group could bypass the order-side trigger above.
CREATE OR REPLACE FUNCTION validate_preorder_checkout_group_link()
RETURNS trigger AS $$
BEGIN
  IF NEW.checkout_group_id IS NOT NULL AND NEW.checkout_group_id IS DISTINCT FROM OLD.checkout_group_id
     AND EXISTS (
       SELECT 1 FROM orders o
       WHERE o.preorder_id = NEW.id
         AND o.checkout_group_id IS DISTINCT FROM NEW.checkout_group_id
     ) THEN
    RAISE EXCEPTION 'preorder checkout group must match every linked service order';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_preorders_validate_checkout_group_link ON preorders;
CREATE TRIGGER trg_preorders_validate_checkout_group_link
BEFORE UPDATE OF checkout_group_id ON preorders
FOR EACH ROW EXECUTE FUNCTION validate_preorder_checkout_group_link();

CREATE OR REPLACE FUNCTION validate_preorder_table_reservation_store()
RETURNS trigger AS $$
DECLARE
  v_preorder_store BIGINT;
  v_table_store BIGINT;
BEGIN
  SELECT store_id INTO v_preorder_store FROM preorders WHERE id = NEW.preorder_id;
  SELECT store_id INTO v_table_store FROM tables WHERE id = NEW.table_id AND is_active = TRUE;
  IF v_preorder_store IS NULL OR v_table_store IS NULL OR v_preorder_store IS DISTINCT FROM v_table_store THEN
    RAISE EXCEPTION 'preorder table must be active and belong to the preorder store';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_preorder_table_reservation_store ON preorder_table_reservations;
CREATE TRIGGER trg_preorder_table_reservation_store
BEFORE INSERT OR UPDATE OF preorder_id, table_id ON preorder_table_reservations
FOR EACH ROW EXECUTE FUNCTION validate_preorder_table_reservation_store();
