-- ==========================================================
-- Migration 0033_preorder_customer_checkin.sql
-- Additive customer check-in requests and slot strike events.
--
-- WARNING: Additive only. Do not edit migrations 0001-0032.
-- Do not alter payment-attempt, review, auth, or catalog tables.
-- All timestamps are TIMESTAMPTZ.
-- ==========================================================

CREATE TABLE IF NOT EXISTS preorder_checkin_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL REFERENCES preorders(id) ON DELETE RESTRICT,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  customer_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  scheduled_start_at TIMESTAMPTZ NOT NULL,
  scheduled_end_at TIMESTAMPTZ NOT NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(40) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'RESCHEDULED')),
  resolved_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT,
  resolved_at TIMESTAMPTZ NULL,
  rejection_reason VARCHAR(500) NULL,
  late_confirmation_reason VARCHAR(500) NULL,
  manager_breach_recorded_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_preorder_checkin_slot UNIQUE (preorder_id, scheduled_start_at)
);

CREATE INDEX IF NOT EXISTS idx_preorder_checkin_requests_due
  ON preorder_checkin_requests(status, scheduled_start_at)
  WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_preorder_checkin_requests_preorder
  ON preorder_checkin_requests(preorder_id, created_at DESC);

COMMENT ON TABLE preorder_checkin_requests IS
  'Customer check-in requests for preorders within [T-30, T+30] arrival window.';

CREATE TABLE IF NOT EXISTS preorder_slot_strike_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preorder_id BIGINT NOT NULL REFERENCES preorders(id) ON DELETE RESTRICT,
  scheduled_start_at TIMESTAMPTZ NOT NULL,
  manager_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  strike_source VARCHAR(40) NOT NULL CHECK (strike_source IN ('CONFIRMATION_BREACH', 'CHECKIN_BREACH')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_preorder_slot_strike UNIQUE (preorder_id, scheduled_start_at)
);

CREATE INDEX IF NOT EXISTS idx_preorder_slot_strike_manager
  ON preorder_slot_strike_events(manager_id, created_at DESC);

COMMENT ON TABLE preorder_slot_strike_events IS
  'Guarantees strike idempotency: at most 1 strike per preorder and scheduled slot across confirmation and checkin breach categories.';
