-- ==========================================================
-- Migration 0038_vietnam_streets.sql
-- Table for storing Vietnam street names by province and district
-- ==========================================================

CREATE TABLE IF NOT EXISTS vietnam_streets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_name VARCHAR(150) NOT NULL,
    district_name VARCHAR(150) NOT NULL,
    street_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vietnam_street UNIQUE (province_name, district_name, street_name)
);

CREATE INDEX IF NOT EXISTS idx_vietnam_streets_lookup
    ON vietnam_streets (province_name, district_name);

CREATE INDEX IF NOT EXISTS idx_vietnam_streets_name
    ON vietnam_streets (street_name);
