/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CuaHangRouteImport } from './routes/cua-hang'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as HoSoRouteImport } from './routes/ho-so'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as TheoDoiDonRouteImport } from './routes/theo-doi-don'
import { Route as TuyenDungRouteImport } from './routes/tuyen-dung'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBepRouteImport } from './routes/admin.bep'
import { Route as AdminCaiDatRouteImport } from './routes/admin.cai-dat'
import { Route as AdminChiNhanhRouteImport } from './routes/admin.chi-nhanh'
import { Route as AdminDonHangRouteImport } from './routes/admin.don-hang'
import { Route as AdminKhuyenMaiRouteImport } from './routes/admin.khuyen-mai'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPosRouteImport } from './routes/admin.pos'
import { Route as AdminThongBaoRouteImport } from './routes/admin.thong-bao'
import { Route as AdminThucDonRouteImport } from './routes/admin.thuc-don'
import { Route as AdminViTriRouteImport } from './routes/admin.vi-tri'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CuaHangRoute = CuaHangRouteImport.update({
  id: '/cua-hang',
  path: '/cua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoRoute = HoSoRouteImport.update({
  id: '/ho-so',
  path: '/ho-so',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoDoiDonRoute = TheoDoiDonRouteImport.update({
  id: '/theo-doi-don',
  path: '/theo-doi-don',
  getParentRoute: () => rootRouteImport,
} as any)
const TuyenDungRoute = TuyenDungRouteImport.update({
  id: '/tuyen-dung',
  path: '/tuyen-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBepRoute = AdminBepRouteImport.update({
  id: '/bep',
  path: '/bep',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaiDatRoute = AdminCaiDatRouteImport.update({
  id: '/cai-dat',
  path: '/cai-dat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChiNhanhRoute = AdminChiNhanhRouteImport.update({
  id: '/chi-nhanh',
  path: '/chi-nhanh',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonHangRoute = AdminDonHangRouteImport.update({
  id: '/don-hang',
  path: '/don-hang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKhuyenMaiRoute = AdminKhuyenMaiRouteImport.update({
  id: '/khuyen-mai',
  path: '/khuyen-mai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThongBaoRoute = AdminThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThucDonRoute = AdminThucDonRouteImport.update({
  id: '/thuc-don',
  path: '/thuc-don',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViTriRoute = AdminViTriRouteImport.update({
  id: '/vi-tri',
  path: '/vi-tri',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cua-hang': typeof CuaHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-so': typeof HoSoRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/theo-doi-don': typeof TheoDoiDonRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/admin/bep': typeof AdminBepRoute
  '/admin/cai-dat': typeof AdminCaiDatRoute
  '/admin/chi-nhanh': typeof AdminChiNhanhRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/khuyen-mai': typeof AdminKhuyenMaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/thong-bao': typeof AdminThongBaoRoute
  '/admin/thuc-don': typeof AdminThucDonRoute
  '/admin/vi-tri': typeof AdminViTriRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-so': typeof HoSoRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/theo-doi-don': typeof TheoDoiDonRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/admin/bep': typeof AdminBepRoute
  '/admin/cai-dat': typeof AdminCaiDatRoute
  '/admin/chi-nhanh': typeof AdminChiNhanhRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/khuyen-mai': typeof AdminKhuyenMaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/thong-bao': typeof AdminThongBaoRoute
  '/admin/thuc-don': typeof AdminThucDonRoute
  '/admin/vi-tri': typeof AdminViTriRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cua-hang': typeof CuaHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-so': typeof HoSoRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/theo-doi-don': typeof TheoDoiDonRoute
  '/tuyen-dung': typeof TuyenDungRoute
  '/admin/bep': typeof AdminBepRoute
  '/admin/cai-dat': typeof AdminCaiDatRoute
  '/admin/chi-nhanh': typeof AdminChiNhanhRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/khuyen-mai': typeof AdminKhuyenMaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/thong-bao': typeof AdminThongBaoRoute
  '/admin/thuc-don': typeof AdminThucDonRoute
  '/admin/vi-tri': typeof AdminViTriRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cua-hang'
    | '/gioi-thieu'
    | '/ho-so'
    | '/menu'
    | '/sitemap.xml'
    | '/thanh-toan'
    | '/theo-doi-don'
    | '/tuyen-dung'
    | '/admin/bep'
    | '/admin/cai-dat'
    | '/admin/chi-nhanh'
    | '/admin/don-hang'
    | '/admin/khuyen-mai'
    | '/admin/login'
    | '/admin/pos'
    | '/admin/thong-bao'
    | '/admin/thuc-don'
    | '/admin/vi-tri'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cua-hang'
    | '/gioi-thieu'
    | '/ho-so'
    | '/menu'
    | '/sitemap.xml'
    | '/thanh-toan'
    | '/theo-doi-don'
    | '/tuyen-dung'
    | '/admin/bep'
    | '/admin/cai-dat'
    | '/admin/chi-nhanh'
    | '/admin/don-hang'
    | '/admin/khuyen-mai'
    | '/admin/login'
    | '/admin/pos'
    | '/admin/thong-bao'
    | '/admin/thuc-don'
    | '/admin/vi-tri'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cua-hang'
    | '/gioi-thieu'
    | '/ho-so'
    | '/menu'
    | '/sitemap.xml'
    | '/thanh-toan'
    | '/theo-doi-don'
    | '/tuyen-dung'
    | '/admin/bep'
    | '/admin/cai-dat'
    | '/admin/chi-nhanh'
    | '/admin/don-hang'
    | '/admin/khuyen-mai'
    | '/admin/login'
    | '/admin/pos'
    | '/admin/thong-bao'
    | '/admin/thuc-don'
    | '/admin/vi-tri'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CuaHangRoute: typeof CuaHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HoSoRoute: typeof HoSoRoute
  MenuRoute: typeof MenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThanhToanRoute: typeof ThanhToanRoute
  TheoDoiDonRoute: typeof TheoDoiDonRoute
  TuyenDungRoute: typeof TuyenDungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cua-hang': {
      id: '/cua-hang'
      path: '/cua-hang'
      fullPath: '/cua-hang'
      preLoaderRoute: typeof CuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so': {
      id: '/ho-so'
      path: '/ho-so'
      fullPath: '/ho-so'
      preLoaderRoute: typeof HoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo-doi-don': {
      id: '/theo-doi-don'
      path: '/theo-doi-don'
      fullPath: '/theo-doi-don'
      preLoaderRoute: typeof TheoDoiDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuyen-dung': {
      id: '/tuyen-dung'
      path: '/tuyen-dung'
      fullPath: '/tuyen-dung'
      preLoaderRoute: typeof TuyenDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bep': {
      id: '/admin/bep'
      path: '/bep'
      fullPath: '/admin/bep'
      preLoaderRoute: typeof AdminBepRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cai-dat': {
      id: '/admin/cai-dat'
      path: '/cai-dat'
      fullPath: '/admin/cai-dat'
      preLoaderRoute: typeof AdminCaiDatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chi-nhanh': {
      id: '/admin/chi-nhanh'
      path: '/chi-nhanh'
      fullPath: '/admin/chi-nhanh'
      preLoaderRoute: typeof AdminChiNhanhRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/don-hang': {
      id: '/admin/don-hang'
      path: '/don-hang'
      fullPath: '/admin/don-hang'
      preLoaderRoute: typeof AdminDonHangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/khuyen-mai': {
      id: '/admin/khuyen-mai'
      path: '/khuyen-mai'
      fullPath: '/admin/khuyen-mai'
      preLoaderRoute: typeof AdminKhuyenMaiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/thong-bao': {
      id: '/admin/thong-bao'
      path: '/thong-bao'
      fullPath: '/admin/thong-bao'
      preLoaderRoute: typeof AdminThongBaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/thuc-don': {
      id: '/admin/thuc-don'
      path: '/thuc-don'
      fullPath: '/admin/thuc-don'
      preLoaderRoute: typeof AdminThucDonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vi-tri': {
      id: '/admin/vi-tri'
      path: '/vi-tri'
      fullPath: '/admin/vi-tri'
      preLoaderRoute: typeof AdminViTriRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBepRoute: typeof AdminBepRoute
  AdminCaiDatRoute: typeof AdminCaiDatRoute
  AdminChiNhanhRoute: typeof AdminChiNhanhRoute
  AdminDonHangRoute: typeof AdminDonHangRoute
  AdminKhuyenMaiRoute: typeof AdminKhuyenMaiRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminThongBaoRoute: typeof AdminThongBaoRoute
  AdminThucDonRoute: typeof AdminThucDonRoute
  AdminViTriRoute: typeof AdminViTriRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBepRoute: AdminBepRoute,
  AdminCaiDatRoute: AdminCaiDatRoute,
  AdminChiNhanhRoute: AdminChiNhanhRoute,
  AdminDonHangRoute: AdminDonHangRoute,
  AdminKhuyenMaiRoute: AdminKhuyenMaiRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPosRoute: AdminPosRoute,
  AdminThongBaoRoute: AdminThongBaoRoute,
  AdminThucDonRoute: AdminThucDonRoute,
  AdminViTriRoute: AdminViTriRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CuaHangRoute: CuaHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  HoSoRoute: HoSoRoute,
  MenuRoute: MenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThanhToanRoute: ThanhToanRoute,
  TheoDoiDonRoute: TheoDoiDonRoute,
  TuyenDungRoute: TuyenDungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
